### ISSUE TITLE
The 'gilt' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by lwm** [metacloud/molecule#1132]
First of all, thanks for molecule, it is simply awesome 👏 👏 👏 

# Issue Type
- Bug report

# Molecule and Ansible details

```
ansible 2.4.3.0
  config file = None
  configured module search path = ['/home/lwm/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/lwm/.local/share/virtualenvs/user--RBEje2m/lib/python3.5/site-packages/ansible
  executable location = /home/lwm/.local/share/virtualenvs/user--RBEje2m/bin/ansible
  python version = 3.5.3 (default, Jan 19 2017, 14:11:04) [GCC 6.3.0 20170118]

(user--RBEje2m) ➜  user molecule --version         
molecule, version 2.8.2
```

- Molecule installation method: pipenv
- Ansible installation method: pipenv

# Desired Behaviour

My dependencies are installed in the molecule roles folder.

# Actual Behaviour (Bug report only)

I have the following in my `molecule.yml`:

```
dependency:
  name: gilt
```

And then a `gilt.yml` in my same `molecule/default` folder (same localtion as `molecule.yml`):

```
---
- git: "https://github.com/juju4/ansible-gpgkey_generate.git"
```

I've got all these packages installed in my virtualenv:

```
ansible = "*"
docker-py = "*"
molecule = "*"
python-gilt = "*"
```

(Where `= "*"` means the latest version).

It blows up with a weird error. Please see below.

```
(user--RBEje2m) ➜  user pipenv run molecule --debug dependency                                                                                                              
--> Test matrix
    b'\n\xe2\x94\x94\xe2\x94\x80\xe2\x94\x80 default\n    \xe2\x94\x94\xe2\x94\x80\xe2\x94\x80 dependency'                                                                                    

--> Scenario: 'default'
--> Action: 'dependency'
DEBUG: ANSIBLE ENVIRONMENT
--- {}

DEBUG: MOLECULE ENVIRONMENT
---
MOLECULE_DEBUG: 'True'
MOLECULE_DEPENDENCY_NAME: gilt
MOLECULE_DRIVER_NAME: docker
MOLECULE_EPHEMERAL_DIRECTORY: /home/lwm/autonomic/user/molecule/default/.molecule
MOLECULE_FILE: /home/lwm/autonomic/user/molecule/default/molecule.yml
MOLECULE_INSTANCE_CONFIG: /home/lwm/autonomic/user/molecule/default/.molecule/instance_config.yml                                                                                             
MOLECULE_INVENTORY_FILE: /home/lwm/autonomic/user/molecule/default/.molecule/ansible_inventory.yml                                                                                            
MOLECULE_LINT_NAME: yamllint
MOLECULE_PROVISIONER_NAME: ansible
MOLECULE_SCENARIO_DIRECTORY: /home/lwm/autonomic/user/molecule/default
MOLECULE_SCENARIO_NAME: default
MOLECULE_VERIFIER_NAME: testinfra

DEBUG: SHELL REPLAY
MOLECULE_DEBUG=True MOLECULE_DEPENDENCY_NAME=gilt MOLECULE_DRIVER_NAME=docker MOLECULE_EPHEMERAL_DIRECTORY=/home/lwm/autonomic/user/molecule/default/.molecule MOLECULE_FILE=/home/lwm/autonomic/user/molecule/default/molecule.yml MOLECULE_INSTANCE_CONFIG=/home/lwm/autonomic/user/molecule/default/.molecule/instance_config.yml MOLECULE_INVENTORY_FILE=/home/lwm/autonomic/user/molecule/default/.molecule/ansible_inventory.yml MOLECULE_LINT_NAME=yamllint MOLECULE_PROVISIONER_NAME=ansible MOLECULE_SCENARIO_DIRECTORY=/home/lwm/autonomic/user/molecule/default MOLECULE_SCENARIO_NAME=default MOLECULE_VERIFIER_NAME=testinfra

DEBUG: COMMAND
/home/lwm/.local/share/virtualenvs/user--RBEje2m/bin/gilt --config=/home/lwm/autonomic/user/molecule/default/gilt.yml --debug overlay   


Traceback (most recent call last):
  File "/home/lwm/.local/share/virtualenvs/user--RBEje2m/lib/python3.5/site-packages/pbr/version.py", line 441, in _get_version_from_pkg_resources
    provider = pkg_resources.get_provider(requirement)
  File "/home/lwm/.local/share/virtualenvs/user--RBEje2m/lib/python3.5/site-packages/pkg_resources/__init__.py", line 436, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/home/lwm/.local/share/virtualenvs/user--RBEje2m/lib/python3.5/site-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/lwm/.local/share/virtualenvs/user--RBEje2m/lib/python3.5/site-packages/pkg_resources/__init__.py", line 870, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'gilt' distribution was not found and is required by the application

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lwm/.local/share/virtualenvs/user--RBEje2m/bin/gilt", line 7, in <module>
    from gilt.shell import main
  File "/home/lwm/.local/share/virtualenvs/user--RBEje2m/lib/python3.5/site-packages/gilt/__init__.py", line 26, in <module>
    __version__ = version_info.release_string()
  File "/home/lwm/.local/share/virtualenvs/user--RBEje2m/lib/python3.5/site-packages/pbr/version.py", line 456, in release_string
    return self.semantic_version().release_string()
  File "/home/lwm/.local/share/virtualenvs/user--RBEje2m/lib/python3.5/site-packages/pbr/version.py", line 461, in semantic_version
    self._semantic = self._get_version_from_pkg_resources()
  File "/home/lwm/.local/share/virtualenvs/user--RBEje2m/lib/python3.5/site-packages/pbr/version.py", line 448, in _get_version_from_pkg_resources
    result_string = packaging.get_version(self.package)
  File "/home/lwm/.local/share/virtualenvs/user--RBEje2m/lib/python3.5/site-packages/pbr/packaging.py", line 748, in get_version
    name=package_name))
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name gilt was given, but was not able to be found.
```

**Comment by lwm** [comment]
Hmm, I just realised that I was doing this through a python 3 install and installed by pipenv.

Both are unsupported ;) Also, I'm not using this Gilt stuff right now, so will close off.
