### ISSUE TITLE
DistributionNotFound: six

### ISSUE THREAD

**Issue by Raffaello** [metacloud/molecule#1150]
# Issue Type

- Bug report

# Molecule and Ansible details
molecule version 2.8.3 
reported by `molecule --version`
```
molecule, version 0.0.1.dev511
```

ansible 2.4 `ansible 2.4.3.0`

- Molecule installation method: pip
- Ansible installation method: OS package

# Actual Behaviour (Bug report only)

```
    The full traceback is:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 88, in run
        items = self._get_loop_items()
      File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 207, in _get_loop_items
        convert_bare=False)
      File "/usr/lib/python2.7/site-packages/ansible/utils/listify.py", line 34, in listify_lookup_plugin_terms
        terms = templar.template(terms.strip(), convert_bare=convert_bare, fail_on_undefined=fail_on_undefined)
      File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 450, in template
        disable_lookups=disable_lookups,
      File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 642, in do_template
        myenv.filters.update(self._get_filters())
      File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 279, in _get_filters
        plugins = [x for x in self._filter_loader.all()]
      File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 426, in all
        self._module_cache[path] = self._load_module_source(name, path)
      File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 339, in _load_module_source
        module = imp.load_source(full_name, path, module_file)
      File "/usr/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/filters/molecule_core.py", line 23, in <module>
        from molecule import interpolation
      File "/usr/lib/python2.7/site-packages/molecule/__init__.py", line 24, in <module>
        __version__ = version_info.release_string()
      File "/usr/lib/python2.7/site-packages/pbr/version.py", line 456, in release_string
        return self.semantic_version().release_string()
      File "/usr/lib/python2.7/site-packages/pbr/version.py", line 461, in semantic_version
        self._semantic = self._get_version_from_pkg_resources()
      File "/usr/lib/python2.7/site-packages/pbr/version.py", line 438, in _get_version_from_pkg_resources
        import pkg_resources
      File "/usr/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 2671, in <module>
        working_set.require(__requires__)
      File "/usr/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 654, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 552, in resolve
        raise DistributionNotFound(req)
    DistributionNotFound: cryptography
```

basically the issue is the `cryptography` package is in `/usr/lib64/python2.7/site-packages/`

python version is 2.7

if i run `python -c 'import cryptography'` run succesfully.

also 
```
python -c "import site; print(site.getsitepackages())"
['/usr/lib64/python2.7/site-packages', '/usr/lib/python2.7/site-packages', '/usr/lib/site-python']
```
module is installed:
```
find /usr/lib64/python2.7/ -name cryptography
/usr/lib64/python2.7/site-packages/cryptography
```

**EDIT**

I was able to fix the previous error with `cryptography` reinstall molecule as `pip --user`.
but now i have `DistributionNotFound` on 

```
DistributionNotFound: six>=1.4.1
    
    fatal: [localhost]: FAILED! => {
        "msg": "Unexpected failure during module execution.", 
        "stdout": ""
    }
```

and six version is `1.11.0`

OUTPUT:

```
The full traceback is:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 88, in run
        items = self._get_loop_items()
      File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 207, in _get_loop_items
        convert_bare=False)
      File "/usr/lib/python2.7/site-packages/ansible/utils/listify.py", line 34, in listify_lookup_plugin_terms
        terms = templar.template(terms.strip(), convert_bare=convert_bare, fail_on_undefined=fail_on_undefined)
      File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 450, in template
        disable_lookups=disable_lookups,
      File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 642, in do_template
        myenv.filters.update(self._get_filters())
      File "/usr/lib/python2.7/site-packages/ansible/template/__init__.py", line 279, in _get_filters
        plugins = [x for x in self._filter_loader.all()]
      File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 426, in all
        self._module_cache[path] = self._load_module_source(name, path)
      File "/usr/lib/python2.7/site-packages/ansible/plugins/loader.py", line 339, in _load_module_source
        module = imp.load_source(full_name, path, module_file)
      File "/home/rbertini/.local/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/filters/molecule_core.py", line 23, in <module>
        from molecule import interpolation
      File "/home/rbertini/.local/lib/python2.7/site-packages/molecule/__init__.py", line 24, in <module>
        __version__ = version_info.release_string()
      File "/usr/lib/python2.7/site-packages/pbr/version.py", line 456, in release_string
        return self.semantic_version().release_string()
      File "/usr/lib/python2.7/site-packages/pbr/version.py", line 461, in semantic_version
        self._semantic = self._get_version_from_pkg_resources()
      File "/usr/lib/python2.7/site-packages/pbr/version.py", line 438, in _get_version_from_pkg_resources
        import pkg_resources
      File "/usr/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 2671, in <module>
        working_set.require(__requires__)
      File "/usr/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 654, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 552, in resolve
        raise DistributionNotFound(req)
    DistributionNotFound: six>=1.4.1
    
    fatal: [localhost]: FAILED! => {
        "msg": "Unexpected failure during module execution.", 
        "stdout": ""
    }
```

**NOTE**: ansible is working properly.

**Comment by retr0h** [comment]
I suggest running this in a virtualenv, see the [quickstart](http://molecule.readthedocs.io/en/latest/#quick-start).

**Comment by Raffaello** [comment]
Thanks... that actually solved my issue.
