### ISSUE TITLE
Issue Convering Molecule 1.25.0 to Molecule 2

### ISSUE THREAD

**Issue by AjG1tHub** [metacloud/molecule#1155]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version 2.4.3.0
molecule --version 2.8.2
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

Molecule should run using the following molecule.yml script
```
---
molecule:
  test:
    sequence:
      - destroy
      - syntax
      - create
      - converge
      - verify
  ignore_paths:
    - .git
    - .vagrant
    - .molecule
    - venv
dependency:
  name: galaxy
driver:
  name: vagrant
vagrant:
  platforms:
    - name: ubuntu/trusty64
      box: trusty64
      box_url: https://vagrantcloud.com/ubuntu/boxes/trusty64/versions/14.04/providers/virtualbox.box
  providers:
    - name: virtualbox
      type: virtualbox
      options:
        memory: 512
        cpus: 2
  instances:
    - name: ansible-role-base-example
      ansible_groups:
        - group1
```
# Actual Behaviour (Bug report only)

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/molecule/command/test.py", line 109, in test
    base.get_configs(args, command_args), scenario_name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/molecule/command/base.py", line 119, in get_configs
    ansible_args=ansible_args, ) for c in glob.glob(MOLECULE_GLOB)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/molecule/config.py", line 91, in __init__
    self.config = self._combine()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/molecule/config.py", line 265, in _combine
    schema.validate(base)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/molecule/model/schema.py", line 199, in validate
    return schema.load(c)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/marshmallow/schema.py", line 580, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/marshmallow/schema.py", line 701, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'vagrant': ['Unknown field'], 'molecule': ['Unknown field']}
```

I apologize if this is some very simple fix, I'm new to both YAML and Molecule

**Comment by retr0h** [comment]
> Molecule should run using the following molecule.yml script

Molecule v2 has a different format.  I suggest creating a new molecule v2 role and looking at the differences.
