### ISSUE TITLE
Molecule Init Failure - UnicodeDecodeError

### ISSUE THREAD

**Issue by nathanwebsterdotme** [metacloud/molecule#1214]
# Issue Type
- Bug report

# Molecule and Ansible details

```
ansible 2.5.0
  config file = None
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/.local/lib/python2.7/site-packages/ansible
  executable location = /home/vagrant/.local/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

```
molecule, version 2.11.0
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Desired Behavior

Initialise new role

# Actual Behaviour (Bug report only)
```
vagrant@ubuntu-xenial:~/ansible/roles$ molecule init role -–role-name nginx
Traceback (most recent call last):
  File "/home/vagrant/.local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 1064, in invoke
    sub_ctx = cmd.make_context(cmd_name, args, parent=ctx)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/core.py", line 876, in parse_args
    opts, args, param_order = parser.parse_args(args=args)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/parser.py", line 267, in parse_args
    self._process_args_for_options(state)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/parser.py", line 293, in _process_args_for_options
    self._process_opts(arg, state)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/parser.py", line 414, in _process_opts
    self._match_long_opt(norm_long_opt, explicit_value, state)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/parser.py", line 324, in _match_long_opt
    raise NoSuchOption(opt, possibilities=possibilities)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/exceptions.py", line 146, in __init__
    UsageError.__init__(self, message, ctx)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/exceptions.py", line 38, in __init__
    ClickException.__init__(self, message)
  File "/home/vagrant/.local/lib/python2.7/site-packages/click/exceptions.py", line 14, in __init__
    message = message.encode('utf-8')
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 17: ordinal not in range(128)
```

**Comment by nathanwebsterdotme** [comment]
Tried this on locally on my mac, and in a ubuntu 16.04 box in vagrant!
