### ISSUE TITLE
unable to set config-file

### ISSUE THREAD

**Issue by Eimert** [metacloud/molecule#1228]
# Issue Type
- Bug report

# Molecule and Ansible details

```
ansible --version
```
2.5.0

```
molecule --version
```
1.11.0

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Desired Behavior

`yamllint -c .yamllint .` or 
```
eimert@EIM ansible-role-awx $ yamllint .
./tests/test-no-playbook.yml
  5:31      warning  truthy value is not quoted  (truthy)

./tasks/main.yml
  17:12     warning  truthy value is not quoted  (truthy)
  18:21     warning  truthy value is not quoted  (truthy)

./tasks/awx-install-playbook.yml
  13:17     warning  truthy value is not quoted  (truthy)

./defaults/main.yml
  5:19      warning  truthy value is not quoted  (truthy)
  6:27      warning  truthy value is not quoted  (truthy)
```
```
eimert@EIM ansible-role-awx $ cat .yamllint 
---
extends: default

ignore: |
  /roles/
  /molecule/
```

# Actual Behaviour (Bug report only)

```
eimert@EIM ansible-role-awx $ molecule test --scenario-name="default"; echo $? 
...snip..
--> Scenario: 'default'
--> Action: 'lint'
--> Executing Yamllint on files found in /home/eimert/dev/ansible-role-awx/...
    /home/eimert/dev/ansible-role-awx/tests/test-no-playbook.yml
      5:31      warning  truthy value is not quoted  (truthy)
    
    /home/eimert/dev/ansible-role-awx/molecule/centos-7/verifier.yml
      18:81     error    line too long (84 > 80 characters)  (line-length)
      19:81     error    line too long (114 > 80 characters)  (line-length)
      45:22     warning  truthy value is not quoted  (truthy)
    
    /home/eimert/dev/ansible-role-awx/molecule/centos-7/destroy.yml
      5:17      warning  truthy value is not quoted  (truthy)
    
    /home/eimert/dev/ansible-role-awx/molecule/centos-7/prepare.yml
      4:17      warning  truthy value is not quoted  (truthy)
    
    /home/eimert/dev/ansible-role-awx/molecule/centos-7/create.yml
      5:17      warning  truthy value is not quoted  (truthy)
      9:81      error    line too long (87 > 80 characters)  (line-length)
      10:81     error    line too long (85 > 80 characters)  (line-length)
      16:81     error    line too long (116 > 80 characters)  (line-length)
      30:81     error    line too long (92 > 80 characters)  (line-length)
      33:81     error    line too long (124 > 80 characters)  (line-length)
      41:19     warning  truthy value is not quoted  (truthy)
      43:81     error    line too long (93 > 80 characters)  (line-length)
... snip ...
```
As you can see, files in the /molecule/ dir are included :-1: 

head default/molecule.yml:
```
---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: .yamllint
```
The default yamllint config files is **also** ignored with this `molecule.yml` setting:
```
lint:
  name: yamllint
```

**Please give some details of what is actually happening.**
It seems molecule neglects the .yamllint config file, even though it is configured. Changing the filename leads to a python FileNotFoundError:
```
--> Executing Yamllint on files found in /home/eimert/dev/ansible-role-awx/...
Traceback (most recent call last):
  File "/usr/local/bin/yamllint", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.5/dist-packages/yamllint/cli.py", line 125, in run
    conf = YamlLintConfig(file=args.config_file)
  File "/usr/local/lib/python3.5/dist-packages/yamllint/config.py", line 36, in __init__
    with open(file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '.yamllindt'
An error occured during the test sequence.  Cleaning up.
```
Identical to `yamllint -c .yamllinat .` It seems molecule feeds the right filename to yamllint. Not sure this error resides in molecule or yamllint.

[code on github](https://github.com/Eimert/ansible-role-awx)<br>
[travis-ci pipeline output (molecule)](https://travis-ci.org/Eimert/ansible-role-awx)

**Comment by retr0h** [comment]
Please migrate to Molecule v2.

**Comment by Eimert** [comment]
@retr0h I'm using the latest version of molecule: `molecule, version 2.12.1`

**Comment by retr0h** [comment]
Can you correct the bug report above to provide the versions you are actually using?

```
molecule --version
```
1.11.0

**Comment by retr0h** [comment]
I'll look at this later today.

**Comment by retr0h** [comment]
Looks like if you change your yamllint file to the following it will work.

```
---
extends: default

ignore: |
  roles/
  molecule/
```

**Comment by Eimert** [comment]
@retr0h issue is now [resolved](https://github.com/Eimert/ansible-role-awx/blob/master/.yamllint) by removing the leading slash (/). Thank you very much :+1:
