### ISSUE TITLE
Cannot locate specified dockerfile error on ubuntu 16.04

### ISSUE THREAD

**Issue by rgooler** [metacloud/molecule#1231]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
```

jenkins@ip-10-100-114-106:~/ansible-role-cleanup$ ansible --version
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/jenkins/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]

```
molecule --version
```
jenkins@ip-10-100-114-106:~/ansible-role-cleanup$ molecule --version
molecule, version 2.12.1

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

molecule test should run on the ubuntu 16.04 jenkins server in AWS just like it does on my local macbook.

The file it complains about being missing is on the filesystem, and is a valid Dockerfile

# Actual Behaviour (Bug report only)

```
    TASK [Build an Ansible compatible image] ***************************************
    task path: /var/lib/jenkins/ansible-role-cleanup/molecule/default/create.yml:38
    Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/docker/docker_image.py
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: jenkins
    <127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/jenkins/.ansible/tmp/ansible-tmp-1522834290.95-141840204649246 `" && echo ansible-tmp-1522834290.95-141840204649246="` echo /var/lib/jenkins/.ansible/tmp/ansible-tmp-1522834290.95-141840204649246 `" ) && sleep 0'
    <127.0.0.1> PUT /var/lib/jenkins/.ansible/tmp/ansible-local-10316zegIj7/tmp5WuO6Z TO /var/lib/jenkins/.ansible/tmp/ansible-tmp-1522834290.95-141840204649246/docker_image.py
    <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /var/lib/jenkins/.ansible/tmp/ansible-tmp-1522834290.95-141840204649246/ /var/lib/jenkins/.ansible/tmp/ansible-tmp-1522834290.95-141840204649246/docker_image.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /var/lib/jenkins/.ansible/tmp/ansible-tmp-1522834290.95-141840204649246/docker_image.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c 'rm -f -r /var/lib/jenkins/.ansible/tmp/ansible-tmp-1522834290.95-141840204649246/ > /dev/null 2>&1 && sleep 0'
    The full traceback is:
    Traceback (most recent call last):
      File "/tmp/ansible__mF8NE/ansible_module_docker_image.py", line 607, in <module>
        main()
      File "/tmp/ansible__mF8NE/ansible_module_docker_image.py", line 602, in main
        ImageManager(client, results)
      File "/tmp/ansible__mF8NE/ansible_module_docker_image.py", line 295, in __init__
        self.present()
      File "/tmp/ansible__mF8NE/ansible_module_docker_image.py", line 323, in present
        self.results['image'] = self.build_image()
      File "/tmp/ansible__mF8NE/ansible_module_docker_image.py", line 525, in build_image
        for line in self.client.build(**params):
      File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 316, in _stream_helper
        yield self._result(response, json=decode)
      File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 231, in _result
        self._raise_for_status(response)
      File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 227, in _raise_for_status
        raise create_api_error_from_http_exception(e)
      File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
        raise cls(e, response=response, explanation=explanation)
    docker.errors.APIError: 500 Server Error: Internal Server Error ("Cannot locate specified Dockerfile: /tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_16_04")

    failed: [localhost] (item={'_ansible_parsed': True, u'changed': False, u'group': u'jenkins', u'uid': 112, 'item': {'image': u'ubuntu:16.04', 'name': u'hostname-ubuntu-16.04'}, 'dest': u'/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_16_04', 'checksum': u'511cce52a4ae4d50cab074ebe5a4e8156823de07', '_ansible_item_result': True, 'failed': False, u'state': u'file', u'gid': 116, u'mode': u'0644', u'invocation': {u'module_args': {u'directory_mode': None, u'force': False, u'remote_src': None, u'path': u'/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_16_04', u'owner': None, u'follow': False, u'group': None, u'unsafe_writes': None, u'serole': None, u'content': None, u'state': u'file', u'diff_peek': None, u'setype': None, u'dest': u'/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_16_04', u'selevel': None, u'original_basename': u'Dockerfile.j2', u'regexp': None, u'validate': None, u'src': u'Dockerfile.j2', u'seuser': None, u'recurse': False, u'delimiter': None, u'mode': None, u'attributes': None, u'backup': None}}, u'owner': u'jenkins', u'path': u'/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_16_04', u'size': 776, 'diff': {u'after': {u'path': u'/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_16_04'}, u'before': {u'path': u'/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_16_04'}}, '_ansible_ignore_errors': None, '_ansible_no_log': False}) => {
        "changed": false,
        "item": {
            "changed": false,
            "checksum": "511cce52a4ae4d50cab074ebe5a4e8156823de07",
            "dest": "/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_16_04",
            "diff": {
                "after": {
                    "path": "/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_16_04"
                },
                "before": {
                    "path": "/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_16_04"
                }
            },
            "failed": false,
            "gid": 116,
            "group": "jenkins",
            "invocation": {
                "module_args": {
                    "attributes": null,
                    "backup": null,
                    "content": null,
                    "delimiter": null,
                    "dest": "/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_16_04",
                    "diff_peek": null,
                    "directory_mode": null,
                    "follow": false,
                    "force": false,
                    "group": null,
                    "mode": null,
                    "original_basename": "Dockerfile.j2",
                    "owner": null,
                    "path": "/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_16_04",
                    "recurse": false,
                    "regexp": null,
                    "remote_src": null,
                    "selevel": null,
                    "serole": null,
                    "setype": null,
                    "seuser": null,
                    "src": "Dockerfile.j2",
                    "state": "file",
                    "unsafe_writes": null,
                    "validate": null
                }
            },
            "item": {
                "image": "ubuntu:16.04",
                "name": "hostname-ubuntu-16.04"
            },
            "mode": "0644",
            "owner": "jenkins",
            "path": "/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_16_04",
            "size": 776,
            "state": "file",
            "uid": 112
        },
        "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible__mF8NE/ansible_module_docker_image.py\", line 607, in <module>\n    main()\n  File \"/tmp/ansible__mF8NE/ansible_module_docker_image.py\", line 602, in main\n    ImageManager(client, results)\n  File \"/tmp/ansible__mF8NE/ansible_module_docker_image.py\", line 295, in __init__\n    self.present()\n  File \"/tmp/ansible__mF8NE/ansible_module_docker_image.py\", line 323, in present\n    self.results['image'] = self.build_image()\n  File \"/tmp/ansible__mF8NE/ansible_module_docker_image.py\", line 525, in build_image\n    for line in self.client.build(**params):\n  File \"/usr/local/lib/python2.7/dist-packages/docker/api/client.py\", line 316, in _stream_helper\n    yield self._result(response, json=decode)\n  File \"/usr/local/lib/python2.7/dist-packages/docker/api/client.py\", line 231, in _result\n    self._raise_for_status(response)\n  File \"/usr/local/lib/python2.7/dist-packages/docker/api/client.py\", line 227, in _raise_for_status\n    raise create_api_error_from_http_exception(e)\n  File \"/usr/local/lib/python2.7/dist-packages/docker/errors.py\", line 31, in create_api_error_from_http_exception\n    raise cls(e, response=response, explanation=explanation)\ndocker.errors.APIError: 500 Server Error: Internal Server Error (\"Cannot locate specified Dockerfile: /tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_16_04\")\n",
        "module_stdout": "",
        "msg": "MODULE FAILURE",
        "rc": 1
    }
    Using module file /usr/lib/python2.7/dist-packages/ansible/modules/cloud/docker/docker_image.py
    <127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /var/lib/jenkins/.ansible/tmp/ansible-tmp-1522834291.27-50562492580974 `" && echo ansible-tmp-1522834291.27-50562492580974="` echo /var/lib/jenkins/.ansible/tmp/ansible-tmp-1522834291.27-50562492580974 `" ) && sleep 0'
    <127.0.0.1> PUT /var/lib/jenkins/.ansible/tmp/ansible-local-10316zegIj7/tmpHgSYv8 TO /var/lib/jenkins/.ansible/tmp/ansible-tmp-1522834291.27-50562492580974/docker_image.py
    <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /var/lib/jenkins/.ansible/tmp/ansible-tmp-1522834291.27-50562492580974/ /var/lib/jenkins/.ansible/tmp/ansible-tmp-1522834291.27-50562492580974/docker_image.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '/usr/bin/python /var/lib/jenkins/.ansible/tmp/ansible-tmp-1522834291.27-50562492580974/docker_image.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c 'rm -f -r /var/lib/jenkins/.ansible/tmp/ansible-tmp-1522834291.27-50562492580974/ > /dev/null 2>&1 && sleep 0'
    The full traceback is:
    Traceback (most recent call last):
      File "/tmp/ansible_mQyO8S/ansible_module_docker_image.py", line 607, in <module>
        main()
      File "/tmp/ansible_mQyO8S/ansible_module_docker_image.py", line 602, in main
        ImageManager(client, results)
      File "/tmp/ansible_mQyO8S/ansible_module_docker_image.py", line 295, in __init__
        self.present()
      File "/tmp/ansible_mQyO8S/ansible_module_docker_image.py", line 323, in present
        self.results['image'] = self.build_image()
      File "/tmp/ansible_mQyO8S/ansible_module_docker_image.py", line 525, in build_image
        for line in self.client.build(**params):
      File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 316, in _stream_helper
        yield self._result(response, json=decode)
      File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 231, in _result
        self._raise_for_status(response)
      File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 227, in _raise_for_status
        raise create_api_error_from_http_exception(e)
      File "/usr/local/lib/python2.7/dist-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
        raise cls(e, response=response, explanation=explanation)
    docker.errors.APIError: 500 Server Error: Internal Server Error ("Cannot locate specified Dockerfile: /tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_18_04")

    failed: [localhost] (item={'_ansible_parsed': True, u'changed': False, u'group': u'jenkins', u'uid': 112, 'item': {'image': u'ubuntu:18.04', 'name': u'hostname-ubuntu-18.04'}, 'dest': u'/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_18_04', 'checksum': u'b103caac6366d8f0df9f73ed411a5c38d10b4959', '_ansible_item_result': True, 'failed': False, u'state': u'file', u'gid': 116, u'mode': u'0644', u'invocation': {u'module_args': {u'directory_mode': None, u'force': False, u'remote_src': None, u'path': u'/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_18_04', u'owner': None, u'follow': False, u'group': None, u'unsafe_writes': None, u'serole': None, u'content': None, u'state': u'file', u'diff_peek': None, u'setype': None, u'dest': u'/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_18_04', u'selevel': None, u'original_basename': u'Dockerfile.j2', u'regexp': None, u'validate': None, u'src': u'Dockerfile.j2', u'seuser': None, u'recurse': False, u'delimiter': None, u'mode': None, u'attributes': None, u'backup': None}}, u'owner': u'jenkins', u'path': u'/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_18_04', u'size': 776, 'diff': {u'after': {u'path': u'/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_18_04'}, u'before': {u'path': u'/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_18_04'}}, '_ansible_ignore_errors': None, '_ansible_no_log': False}) => {
        "changed": false,
        "item": {
            "changed": false,
            "checksum": "b103caac6366d8f0df9f73ed411a5c38d10b4959",
            "dest": "/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_18_04",
            "diff": {
                "after": {
                    "path": "/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_18_04"
                },
                "before": {
                    "path": "/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_18_04"
                }
            },
            "failed": false,
            "gid": 116,
            "group": "jenkins",
            "invocation": {
                "module_args": {
                    "attributes": null,
                    "backup": null,
                    "content": null,
                    "delimiter": null,
                    "dest": "/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_18_04",
                    "diff_peek": null,
                    "directory_mode": null,
                    "follow": false,
                    "force": false,
                    "group": null,
                    "mode": null,
                    "original_basename": "Dockerfile.j2",
                    "owner": null,
                    "path": "/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_18_04",
                    "recurse": false,
                    "regexp": null,
                    "remote_src": null,
                    "selevel": null,
                    "serole": null,
                    "setype": null,
                    "seuser": null,
                    "src": "Dockerfile.j2",
                    "state": "file",
                    "unsafe_writes": null,
                    "validate": null
                }
            },
            "item": {
                "image": "ubuntu:18.04",
                "name": "hostname-ubuntu-18.04"
            },
            "mode": "0644",
            "owner": "jenkins",
            "path": "/tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_18_04",
            "size": 776,
            "state": "file",
            "uid": 112
        },
        "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_mQyO8S/ansible_module_docker_image.py\", line 607, in <module>\n    main()\n  File \"/tmp/ansible_mQyO8S/ansible_module_docker_image.py\", line 602, in main\n    ImageManager(client, results)\n  File \"/tmp/ansible_mQyO8S/ansible_module_docker_image.py\", line 295, in __init__\n    self.present()\n  File \"/tmp/ansible_mQyO8S/ansible_module_docker_image.py\", line 323, in present\n    self.results['image'] = self.build_image()\n  File \"/tmp/ansible_mQyO8S/ansible_module_docker_image.py\", line 525, in build_image\n    for line in self.client.build(**params):\n  File \"/usr/local/lib/python2.7/dist-packages/docker/api/client.py\", line 316, in _stream_helper\n    yield self._result(response, json=decode)\n  File \"/usr/local/lib/python2.7/dist-packages/docker/api/client.py\", line 231, in _result\n    self._raise_for_status(response)\n  File \"/usr/local/lib/python2.7/dist-packages/docker/api/client.py\", line 227, in _raise_for_status\n    raise create_api_error_from_http_exception(e)\n  File \"/usr/local/lib/python2.7/dist-packages/docker/errors.py\", line 31, in create_api_error_from_http_exception\n    raise cls(e, response=response, explanation=explanation)\ndocker.errors.APIError: 500 Server Error: Internal Server Error (\"Cannot locate specified Dockerfile: /tmp/molecule/ansible-role-cleanup/default/Dockerfile_ubuntu_18_04\")\n",
        "module_stdout": "",
        "msg": "MODULE FAILURE",
        "rc": 1
    }
```

**Comment by retr0h** [comment]
Looks like this was resolved per conversation in #molecule-users on freenode.

As the Molecule [quick start](http://molecule.readthedocs.io/en/latest/#quick-start) states, the `docker-py` pip module is needed.  Looks like this module was not installed on the server instance.
