### ISSUE TITLE
Unable to create project directory '{{cookiecutter.repo_name}}'. Error message: 'dict object' has no attribute 'repo_name'. 

### ISSUE THREAD

**Issue by SiM22** [metacloud/molecule#1232]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/simonga/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 14:43:05) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

```
molecule --version
molecule, version 2.12.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip
- OS package

# Desired Behavior

Please give some details of the feature being requested or what
should happen if providing a bug report.

Creating a new scenario throws an error stating undefined variable.

```molecule init scenario -r ansible-java -s default -d docker --verifier-name testinfra
--> Initializing new scenario default...
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/molecule/command/init/scenario.py", line 164, in scenario
    s.execute()
  File "/usr/local/lib/python2.7/site-packages/molecule/command/init/scenario.py", line 79, in execute
    self._process_templates('molecule', self._command_args, role_directory)
  File "/usr/local/lib/python2.7/site-packages/molecule/command/init/base.py", line 61, in _process_templates
    no_input=True,
  File "/usr/local/lib/python2.7/site-packages/cookiecutter/main.py", line 91, in cookiecutter
    output_dir=output_dir
  File "/usr/local/lib/python2.7/site-packages/cookiecutter/generate.py", line 273, in generate_files
    raise UndefinedVariableInTemplate(msg, err, context)
cookiecutter.exceptions.UndefinedVariableInTemplate: Unable to create project directory '{{cookiecutter.repo_name}}'. Error message: 'dict object' has no attribute 'repo_name'. Context: {u'cookiecutter': {u'verifier_lint_name': u'flake8', u'verifier_name': u'testinfra', u'provisioner_name': u'ansible', u'driver_name': u'docker', u'dependency_name': u'galaxy', u'lint_name': u'yamllint', u'provisioner_lint_name': u'ansible-lint', u'scenario_name': u'default', u'role_name': u'ansible-java', u'molecule_directory': u'molecule'}}
```

**Comment by SiM22** [comment]
I have fixed this

For some reason the contents of the following directory looked like this

``` usr/local/lib/python2.7/site-packages/molecule/cookiecutter/verifier/goss  ls -l
total 8
-rw-r--r--  1 simonga  admin  176 Apr 19  2017 cookiecutter.json
drwxr-xr-x  4 simonga  admin  128 Apr 19  2017 {{cookiecutter.repo_name}}
```

Fix was
```
rm -rf  usr/local/lib/python2.7/site-packages/molecule/cookiecutter
pip install molecule --force --upgrade
```

**Comment by retr0h** [comment]
Install molecule with a virtualenv.  It's in the quickstart.  Please follow the instructions, you're only asking for issues otherwise.
