### ISSUE TITLE
Build an Ansible compatible image - Cannot locate specified Dockerfile

### ISSUE THREAD

**Issue by priorityinterrupt** [metacloud/molecule#1242]
# Issue Type

- Bug report

# Molecule and Ansible details

```
Operating System: macOS 10.13.4
Python: Python 2.7.10
ansible 2.5.0
molecule: molecule, version 2.12.1
Docker: 18.03.0-ce-mac60
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Run `molecule test` on newly initialized role successfully.  

# Actual Behaviour (Bug report only)

I am unable to complete the task `Build an Ansible compatible image` when running `molecule test`. After initializing a new role I am receiving the following error:

```Cannot locate specified Dockerfile: /var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/molecule/test-role/default/Dockerfile_centos_7```

I have verified that this Dockerfile does exist on my system. 

Steps to Reproduce

```
mkdir molecule_test
cd molecule_test/
pipenv --two
pipenv install molecule ansible docker
pipenv run molecule init role --role-name test-role --driver-name docker --verifier-name testinfra
cd test-role/
pipenv run molecule test
```

```
    TASK [Build an Ansible compatible image] ***************************************
    task path: /Users/digitaladdictions/molecule_test/test-role/molecule/default/create.yml:33
    Using module file /Users/digitaladdictions/.local/share/virtualenvs/molecule_test-gmVLx5yw/lib/python2.7/site-packages/ansible/modules/cloud/docker/docker_image.py
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: digitaladdictions
    <127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /Users/digitaladdictions/.ansible/tmp/ansible-tmp-1523397868.73-114608916090261 `" && echo ansible-tmp-1523397868.73-114608916090261="` echo /Users/digitaladdictions/.ansible/tmp/ansible-tmp-1523397868.73-114608916090261 `" ) && sleep 0'
    <127.0.0.1> PUT /Users/digitaladdictions/.ansible/tmp/ansible-local-56469xfeka0/tmpBp_AZh TO /Users/digitaladdictions/.ansible/tmp/ansible-tmp-1523397868.73-114608916090261/docker_image.py
    <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /Users/digitaladdictions/.ansible/tmp/ansible-tmp-1523397868.73-114608916090261/ /Users/digitaladdictions/.ansible/tmp/ansible-tmp-1523397868.73-114608916090261/docker_image.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '/Users/digitaladdictions/.local/share/virtualenvs/molecule_test-gmVLx5yw/bin/python /Users/digitaladdictions/.ansible/tmp/ansible-tmp-1523397868.73-114608916090261/docker_image.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c 'rm -f -r /Users/digitaladdictions/.ansible/tmp/ansible-tmp-1523397868.73-114608916090261/ > /dev/null 2>&1 && sleep 0'
    The full traceback is:
    Traceback (most recent call last):
      File "/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/ansible_7ObsZm/ansible_module_docker_image.py", line 607, in <module>
        main()
      File "/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/ansible_7ObsZm/ansible_module_docker_image.py", line 602, in main
        ImageManager(client, results)
      File "/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/ansible_7ObsZm/ansible_module_docker_image.py", line 295, in __init__
        self.present()
      File "/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/ansible_7ObsZm/ansible_module_docker_image.py", line 323, in present
        self.results['image'] = self.build_image()
      File "/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/ansible_7ObsZm/ansible_module_docker_image.py", line 525, in build_image
        for line in self.client.build(**params):
      File "/Users/digitaladdictions/.local/share/virtualenvs/molecule_test-gmVLx5yw/lib/python2.7/site-packages/docker/api/client.py", line 316, in _stream_helper
        yield self._result(response, json=decode)
      File "/Users/digitaladdictions/.local/share/virtualenvs/molecule_test-gmVLx5yw/lib/python2.7/site-packages/docker/api/client.py", line 231, in _result
        self._raise_for_status(response)
      File "/Users/digitaladdictions/.local/share/virtualenvs/molecule_test-gmVLx5yw/lib/python2.7/site-packages/docker/api/client.py", line 227, in _raise_for_status
        raise create_api_error_from_http_exception(e)
      File "/Users/digitaladdictions/.local/share/virtualenvs/molecule_test-gmVLx5yw/lib/python2.7/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
        raise cls(e, response=response, explanation=explanation)
    docker.errors.APIError: 500 Server Error: Internal Server Error ("Cannot locate specified Dockerfile: /var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/molecule/test-role/default/Dockerfile_centos_7")

    failed: [localhost] (item={'_ansible_parsed': True, u'changed': False, u'group': u'staff', u'uid': 501, 'item': {'image': u'centos:7', 'name': u'instance'}, 'dest': u'/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/molecule/test-role/default/Dockerfile_centos_7', 'checksum': u'92bbda64c044759fddbb2411f0ec18cc32be7181', '_ansible_item_result': True, 'failed': False, u'state': u'file', u'gid': 20, u'mode': u'0644', u'invocation': {u'module_args': {u'directory_mode': None, u'force': False, u'remote_src': None, u'path': u'/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/molecule/test-role/default/Dockerfile_centos_7', u'owner': None, u'follow': False, u'group': None, u'unsafe_writes': None, u'serole': None, u'content': None, u'state': u'file', u'diff_peek': None, u'setype': None, u'dest': u'/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/molecule/test-role/default/Dockerfile_centos_7', u'selevel': None, u'original_basename': u'Dockerfile.j2', u'regexp': None, u'validate': None, u'src': u'Dockerfile.j2', u'seuser': None, u'recurse': False, u'delimiter': None, u'mode': None, u'attributes': None, u'backup': None}}, u'owner': u'digitaladdictions', u'path': u'/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/molecule/test-role/default/Dockerfile_centos_7', u'size': 772, 'diff': {u'after': {u'path': u'/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/molecule/test-role/default/Dockerfile_centos_7'}, u'before': {u'path': u'/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/molecule/test-role/default/Dockerfile_centos_7'}}, '_ansible_ignore_errors': None, '_ansible_no_log': False}) => {
        "changed": false,
        "item": {
            "changed": false,
            "checksum": "92bbda64c044759fddbb2411f0ec18cc32be7181",
            "dest": "/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/molecule/test-role/default/Dockerfile_centos_7",
            "diff": {
                "after": {
                    "path": "/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/molecule/test-role/default/Dockerfile_centos_7"
                },
                "before": {
                    "path": "/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/molecule/test-role/default/Dockerfile_centos_7"
                }
            },
            "failed": false,
            "gid": 20,
            "group": "staff",
            "invocation": {
                "module_args": {
                    "attributes": null,
                    "backup": null,
                    "content": null,
                    "delimiter": null,
                    "dest": "/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/molecule/test-role/default/Dockerfile_centos_7",
                    "diff_peek": null,
                    "directory_mode": null,
                    "follow": false,
                    "force": false,
                    "group": null,
                    "mode": null,
                    "original_basename": "Dockerfile.j2",
                    "owner": null,
                    "path": "/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/molecule/test-role/default/Dockerfile_centos_7",
                    "recurse": false,
                    "regexp": null,
                    "remote_src": null,
                    "selevel": null,
                    "serole": null,
                    "setype": null,
                    "seuser": null,
                    "src": "Dockerfile.j2",
                    "state": "file",
                    "unsafe_writes": null,
                    "validate": null
                }
            },
            "item": {
                "image": "centos:7",
                "name": "instance"
            },
            "mode": "0644",
            "owner": "digitaladdictions",
            "path": "/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/molecule/test-role/default/Dockerfile_centos_7",
            "size": 772,
            "state": "file",
            "uid": 501
        },
        "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/ansible_7ObsZm/ansible_module_docker_image.py\", line 607, in <module>\n    main()\n  File \"/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/ansible_7ObsZm/ansible_module_docker_image.py\", line 602, in main\n    ImageManager(client, results)\n  File \"/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/ansible_7ObsZm/ansible_module_docker_image.py\", line 295, in __init__\n    self.present()\n  File \"/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/ansible_7ObsZm/ansible_module_docker_image.py\", line 323, in present\n    self.results['image'] = self.build_image()\n  File \"/var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/ansible_7ObsZm/ansible_module_docker_image.py\", line 525, in build_image\n    for line in self.client.build(**params):\n  File \"/Users/digitaladdictions/.local/share/virtualenvs/molecule_test-gmVLx5yw/lib/python2.7/site-packages/docker/api/client.py\", line 316, in _stream_helper\n    yield self._result(response, json=decode)\n  File \"/Users/digitaladdictions/.local/share/virtualenvs/molecule_test-gmVLx5yw/lib/python2.7/site-packages/docker/api/client.py\", line 231, in _result\n    self._raise_for_status(response)\n  File \"/Users/digitaladdictions/.local/share/virtualenvs/molecule_test-gmVLx5yw/lib/python2.7/site-packages/docker/api/client.py\", line 227, in _raise_for_status\n    raise create_api_error_from_http_exception(e)\n  File \"/Users/digitaladdictions/.local/share/virtualenvs/molecule_test-gmVLx5yw/lib/python2.7/site-packages/docker/errors.py\", line 31, in create_api_error_from_http_exception\n    raise cls(e, response=response, explanation=explanation)\ndocker.errors.APIError: 500 Server Error: Internal Server Error (\"Cannot locate specified Dockerfile: /var/folders/5f/lg8qkglx2lj_8kf86zl03_480000gn/T/molecule/test-role/default/Dockerfile_centos_7\")\n",
        "module_stdout": "",
        "msg": "MODULE FAILURE",
        "rc": 1
    }

    PLAY RECAP *********************************************************************
    localhost                  : ok=2    changed=0    unreachable=0    failed=1


ERROR:
An error occured during the test sequence.  Cleaning up.
--> Scenario: 'default'
--> Action: 'destroy'
```

**Comment by retr0h** [comment]
See #1231

**Comment by priorityinterrupt** [comment]
You are correct. I installed docker not docker-py. It works now.
