### ISSUE TITLE
molecule destroy failing with yaml.parser.ParserError

### ISSUE THREAD

**Issue by r0ckyte** [metacloud/molecule#1243]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.4.1.0
```

```
molecule, version 2.3.1
```

Molecule installation method (one of):

- source
- pip

Ansible installation method (one of):

- source
- pip

# Actual Behaviour (Bug report only)

I'm running molecule in 4 scenario's via jenkins job. I observed with "molecule destroy " is failing with yaml parse error while reading state.yml.  This happened to me like 4 times in 110 builds.  here is full stack trace for the error

looks like **state.yml** is being corrupted while execution, any help would be greate

```
+ molecule destroy --scenario-name skynet
--> Test matrix
    
└── prod
    └── destroy
    
--> Inventory /var/lib/jenkins/workspace/Ansible Molecule Tests/ansible/molecule/prod/.molecule/../../../prod/group_vars linked to /var/lib/jenkins/workspace/Ansible Molecule Tests/ansible/molecule/prod/.molecule/group_vars
--> Scenario: 'prod'
--> Action: 'destroy'
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/destroy.py", line 107, in destroy
    base.execute_subcommand(scenario.config, term)
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/base.py", line 99, in execute_subcommand
    return command(config).execute()
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/destroy.py", line 62, in execute
    self.prune()
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/base.py", line 65, in prune
    self._config.state.state_file,
  File "/usr/local/lib/python2.7/dist-packages/molecule/config.py", line 197, in state
    return state.State(self)
  File "/usr/local/lib/python2.7/dist-packages/molecule/state.py", line 68, in __init__
    self._data = self._get_data()
  File "/usr/local/lib/python2.7/dist-packages/molecule/state.py", line 120, in _get_data
    return self._load_file()
  File "/usr/local/lib/python2.7/dist-packages/molecule/state.py", line 132, in _load_file
    return util.safe_load_file(self.state_file)
  File "/usr/local/lib/python2.7/dist-packages/molecule/util.py", line 186, in safe_load_file
    return safe_load(stream)
  File "/usr/local/lib/python2.7/dist-packages/molecule/util.py", line 175, in safe_load
    return yaml.safe_load(string) or {}
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 93, in safe_load
    return load(stream, SafeLoader)
  File "/usr/local/lib/python2.7/dist-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/usr/local/lib/python2.7/dist-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/usr/local/lib/python2.7/dist-packages/yaml/composer.py", line 39, in get_single_node
    if not self.check_event(StreamEndEvent):
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/usr/local/lib/python2.7/dist-packages/yaml/parser.py", line 174, in parse_document_start
    self.peek_token().start_mark)
yaml.parser.ParserError: expected '<document start>', but found '<block mapping start>'
  in "/var/lib/jenkins/workspace/Ansible Molecule Tests/ansible/molecule/prod/.molecule/state.yml", line 4, column 1
 ```

Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.

**Comment by retr0h** [comment]
Please upgrade to a newer version of Molecule.

2.3.1 is old.  2.12.1 is the current release.
