### ISSUE TITLE
Handle Vagrant provider errors

### ISSUE THREAD

**Issue by baccenfutter** [metacloud/molecule#1245]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
2.5.0
```

```
molecule --version
molecule, version 2.12.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

When Vagrant detects and reports a provider error, Molecule should handle that error and throw an error message at the user with a clear, concise and human-readable hint pointing to the actual cause of the issue.

# Actual Behaviour (Bug report only)

When issuing a `vagrant up --provider=virtualbox` and Vagrant detects the the desired provider (VirtualBox) is available in only unsupported versions, it throws a clear, concise and human-readable error message pointing to the actual cause of the problem. Molecule just throws a `python-vagrant` stack-trace that contains no indication of the actual cause what so ever and renders the user completely clueless about what the heck is going on.

**Comment by retr0h** [comment]
I'm going to need more info here.  Need to know how to reproduce the error you are seeing so that a nice message can be reported.   Unfortunately, I cannot capture any possible error vagrant may report, and provide a nice message as part of this bug report.

**Comment by baccenfutter** [comment]
Example using `vagrant-1.8.1` in combination with `virtualbox-5.1`:
```
# molecule create
    [...]
    The full traceback is:
    Traceback (most recent call last):
      File "/tmp/ansible_AyuYHB/ansible_module_molecule_vagrant.py", line 476, in <module>
        main()
      File "/tmp/ansible_AyuYHB/ansible_module_molecule_vagrant.py", line 469, in main
        v.up()
      File "/tmp/ansible_AyuYHB/ansible_module_molecule_vagrant.py", line 334, in up
        cd = self._created()
      File "/tmp/ansible_AyuYHB/ansible_module_molecule_vagrant.py", line 369, in _created
        status = self._status()
      File "/tmp/ansible_AyuYHB/ansible_module_molecule_vagrant.py", line 364, in _status
        s = self._vagrant.status(vm_name=instance_name)[0]
      File "/home/brian/.virtualenvs/playbook-programmfabrik/local/lib/python2.7/site-packages/vagrant/__init__.py", line 493, in status
        output = self._run_vagrant_command(['status', '--machine-readable', vm_name])
      File "/home/brian/.virtualenvs/playbook-programmfabrik/local/lib/python2.7/site-packages/vagrant/__init__.py", line 976, in _run_vagrant_command
        env=self.env, stderr=err_fh))
      File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['/usr/bin/vagrant', 'status', '--machine-readable', 'instance']' returned non-zero exit status 1
    
    failed: [localhost] (item={'box': u'ubuntu/xenial64', 'name': u'instance'}) => {
        "changed": false, 
        "item": {
            "box": "ubuntu/xenial64", 
            "name": "instance"
        }, 
        "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_AyuYHB/ansible_module_molecule_vagrant.py\", line 476, in <module>\n    main()\n  File \"/tmp/ansible_AyuYHB/ansible_module_molecule_vagrant.py\", line 469, in main\n    v.up()\n  File \"/tmp/ansible_AyuYHB/ansible_module_molecule_vagrant.py\", line 334, in up\n    cd = self._created()\n  File \"/tmp/ansible_AyuYHB/ansible_module_molecule_vagrant.py\", line 369, in _created\n    status = self._status()\n  File \"/tmp/ansible_AyuYHB/ansible_module_molecule_vagrant.py\", line 364, in _status\n    s = self._vagrant.status(vm_name=instance_name)[0]\n  File \"/home/brian/.virtualenvs/playbook-programmfabrik/local/lib/python2.7/site-packages/vagrant/__init__.py\", line 493, in status\n    output = self._run_vagrant_command(['status', '--machine-readable', vm_name])\n  File \"/home/brian/.virtualenvs/playbook-programmfabrik/local/lib/python2.7/site-packages/vagrant/__init__.py\", line 976, in _run_vagrant_command\n    env=self.env, stderr=err_fh))\n  File \"/usr/lib/python2.7/subprocess.py\", line 574, in check_output\n    raise CalledProcessError(retcode, cmd, output=output)\nsubprocess.CalledProcessError: Command '['/usr/bin/vagrant', 'status', '--machine-readable', 'instance']' returned non-zero exit status 1\n", 
        "module_stdout": "--> Validating schema /home/brian/src/github.com/programmfabrik/playbook-programmfabrik/roles/role-easydb/molecule/default/molecule.yml.\nValidation completed successfully.\n", 
        "msg": "MODULE FAILURE", 
        "rc": 1
    }


# vagrant up --provider=virtualbox
The provider 'virtualbox' that was requested to back the machine
'default' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0

A Vagrant update may also be available that adds support for the version
you specified. Please check www.vagrantup.com/downloads.html to download
the latest version.
```
