### ISSUE TITLE
Creating machines with virtualbox fails

### ISSUE THREAD

**Issue by loomsen** [metacloud/molecule#1284]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/user/python-venv/ansible-2.5/lib/python2.7/site-packages/ansible
  executable location = /home/user/python-venv/ansible-2.5/bin/ansible
  python version = 2.7.14 (default, Mar 14 2018, 16:45:33) [GCC 8.0.1 20180222 (Red Hat 8.0.1-0.16)]

```

```
molecule, version 2.13.1
```

Molecule installation method (one of):

- pip

Ansible installation method (one of):

- pip

# Desired Behavior

Create a VM in Virtualbox

# Actual Behaviour

Creation of a VM fails with following output:

```
    The full traceback is:
    Traceback (most recent call last):
      File "/tmp/ansible_0c37dT/ansible_module_molecule_vagrant.py", line 541, in <module>
        main()
      File "/tmp/ansible_0c37dT/ansible_module_molecule_vagrant.py", line 531, in main
        v.up()
      File "/tmp/ansible_0c37dT/ansible_module_molecule_vagrant.py", line 373, in up
        if not self._created():
      File "/tmp/ansible_0c37dT/ansible_module_molecule_vagrant.py", line 422, in _created
        status = self._status()
      File "/tmp/ansible_0c37dT/ansible_module_molecule_vagrant.py", line 417, in _status
        s = self._vagrant.status(vm_name=instance_name)[0]
      File "/home/user/python-venv/ansible-2.5/lib/python2.7/site-packages/vagrant/__init__.py", line 494, in status
        return self._parse_status(output)
      File "/home/user/python-venv/ansible-2.5/lib/python2.7/site-packages/vagrant/__init__.py", line 501, in _parse_status
        parsed = self._parse_machine_readable_output(output)
      File "/home/user/python-venv/ansible-2.5/lib/python2.7/site-packages/vagrant/__init__.py", line 899, in _parse_machine_readable_output
        parsed_lines = [line.split(',', 4) for line in output.splitlines() if line.strip()]
    AttributeError: 'NoneType' object has no attribute 'splitlines'
    
    failed: [localhost] (item={'box': u'centos/7', 'name': u'instance'}) => {
        "changed": false, 
        "item": {
            "box": "centos/7", 
            "name": "instance"
        }, 
        "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_0c37dT/ansible_module_molecule_vagrant.py\", line 541, in <module>\n    main()\n  File \"/tmp/ansible_0c37dT/ansible_module_molecule_vagrant.py\", line 531, in main\n    v.up()\n  File \"/tmp/ansible_0c37dT/ansible_module_molecule_vagrant.py\", line 373, in up\n    if not self._created():\n  File \"/tmp/ansible_0c37dT/ansible_module_molecule_vagrant.py\", line 422, in _created\n    status = self._status()\n  File \"/tmp/ansible_0c37dT/ansible_module_molecule_vagrant.py\", line 417, in _status\n    s = self._vagrant.status(vm_name=instance_name)[0]\n  File \"/home/user/python-venv/ansible-2.5/lib/python2.7/site-packages/vagrant/__init__.py\", line 494, in status\n    return self._parse_status(output)\n  File \"/home/user/python-venv/ansible-2.5/lib/python2.7/site-packages/vagrant/__init__.py\", line 501, in _parse_status\n    parsed = self._parse_machine_readable_output(output)\n  File \"/home/user/python-venv/ansible-2.5/lib/python2.7/site-packages/vagrant/__init__.py\", line 899, in _parse_machine_readable_output\n    parsed_lines = [line.split(',', 4) for line in output.splitlines() if line.strip()]\nAttributeError: 'NoneType' object has no attribute 'splitlines'\n", 
        "module_stdout": "--> Validating schema /home/user/git.example.de/example_deployment/roles/backend_loadbalancer/molecule/virtualbox/molecule.yml.\nValidation completed successfully.\n", 
        "msg": "MODULE FAILURE", 
        "rc": 1
    }
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1   
    
    
ERROR: 
```

My molecule.yml is default, I didn't change anything but the box name after init scenario:

```
---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: instance
    box: centos/7
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: virtualbox
verifier:
  name: testinfra
  lint:
    name: flake8

```

There's also a [post on reddit with this bug](https://www.reddit.com/r/ansible/comments/8h3s8b/testing_with_molecule_20_vagrant_should_it_create/)

**Comment by loomsen** [comment]
Hi John,

well, actually there's no machine provisioned, so the output of vagrant status tells me to init a Vagrant environment first. So this is prior to vagrant up.

**Comment by retr0h** [comment]
I have no valid information to go on to address this.  All of the Molecule functional tests pass.  I cannot reproduce.
