### ISSUE TITLE
Verbose in molecule.yml should handle bool True

### ISSUE THREAD

**Issue by zochao** [metacloud/molecule#134]
https://github.com/metacloud/molecule/blob/master/molecule/ansible_playbook.py#L104

```
clearly string +bool isn't gonna work. And it will have error like
Traceback (most recent call last):
File "/Users/zochao/.virtualenvs/metamole/bin/molecule", line 10, in <module>
sys.exit(main())
File "/Users/zochao/metamole/molecule/molecule/cli.py", line 66, in main
CLI().main()
File "/Users/zochao/metamole/molecule/molecule/cli.py", line 62, in main
sys.exit(c.execute())
File "/Users/zochao/metamole/molecule/molecule/commands.py", line 393, in execute
c.execute()
File "/Users/zochao/metamole/molecule/molecule/commands.py", line 224, in execute
ansible = AnsiblePlaybook(self.molecule._config.config['ansible'])
File "/Users/zochao/metamole/molecule/molecule/ansible_playbook.py", line 51, in _init_
self.parse_arg(k, v)
File "/Users/zochao/metamole/molecule/molecule/ansible_playbook.py", line 104, in parse_arg
self.cli_pos.append('-' + value)
TypeError: cannot concatenate 'str' and 'bool' objects
```

**Comment by zochao** [comment]
https://github.com/metacloud/molecule/pull/133

**Comment by abrown-sg** [comment]
<img width="737" alt="screen shot 2016-03-08 at 3 43 54 pm" src="https://cloud.githubusercontent.com/assets/5855384/13620444/9e2f6c32-e544-11e5-91bc-4ea2da2e2262.png">

The documentation incorrectly references this.  It should be v - vvvv.  However I think we should also accept True and make it 'vvvv.'

```python
# verbose is weird, must be -vvvv not verbose=vvvv
if name == 'verbose' and value:
    if value is True:
        value = 'vvvv'
    self.cli_pos.append('-' + value)
```
