### ISSUE TITLE
Cannot lint playbooks and roles with ansible-lint

### ISSUE THREAD

**Issue by nmulvihill** [metacloud/molecule#1343]
# Issue Type
- Feature request

# Molecule and Ansible details

```
ansible --version
2.3.1
```

```
molecule --version
2.15.0
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Desired Behavior
When specifying a different linter in molecule.yml (not the provisioner or verifyer linter), I would like to be able to use ansible-lint. I have some custom ansible-lint rules that I would want ran against the Playbook/role before running the tests, but when I specify ansible-lint, the run fails.

# Actual Behaviour (Bug report only)
molecule.yml:
```
lint:
  name: ansible-lint
  options:
    r: ../some/path/to/lint_rules
    force-color: True
```

molecule --debug lint:
```
Validation completed successfully.
Traceback (most recent call last):
  File "/home/username/miniconda2/envs/molecule2.3/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/home/username/miniconda2/envs/molecule2.3/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/username/miniconda2/envs/molecule2.3/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/username/miniconda2/envs/molecule2.3/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/username/miniconda2/envs/molecule2.3/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/username/miniconda2/envs/molecule2.3/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/username/miniconda2/envs/molecule2.3/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/username/miniconda2/envs/molecule2.3/lib/python2.7/site-packages/molecule/command/lint.py", line 101, in lint
    base.get_configs(args, command_args), scenario_name)
  File "/home/username/miniconda2/envs/molecule2.3/lib/python2.7/site-packages/molecule/command/base.py", line 121, in get_configs
    ) for c in glob.glob(MOLECULE_GLOB)
  File "/home/username/miniconda2/envs/molecule2.3/lib/python2.7/site-packages/molecule/config.py", line 61, in __call__
    obj.after_init()
  File "/home/username/miniconda2/envs/molecule2.3/lib/python2.7/site-packages/molecule/config.py", line 107, in after_init
    self.config = self._reget_config()
  File "/home/username/miniconda2/envs/molecule2.3/lib/python2.7/site-packages/molecule/config.py", line 280, in _reget_config
    env = util.merge_dicts(os.environ.copy(), self.env)
  File "/home/username/miniconda2/envs/molecule2.3/lib/python2.7/site-packages/molecule/config.py", line 189, in env
    'MOLECULE_LINT_NAME': self.lint.name,
AttributeError: 'NoneType' object has no attribute 'name'

```

**Comment by nmulvihill** [comment]
I would like to add that I have added these same lines into the provisioner with no results. It exits silently on checks that I know should be failing.

**Comment by retr0h** [comment]
You cannot change the linter here.  Molecule doesn't support any other linter in this section than yamllint.  Ansible-lint is specific to the provisioner. if you wish to run ansible-lint, then keep it in the provisioner.lint section.

However, there is a bug where Molecule's schema validator isn't reporting this.

**Comment by nmulvihill** [comment]
Even when I keep it in the Provisioner.lint section it never runs. I will remove all other linting from the YAML file and only have the provisioner.lint.name  set to ansible-lint and when I run ```molecule lint``` it will run yamllint

**Comment by retr0h** [comment]
Please open a different bug with proper details and working code to reproduce.  As for this ticket, you are configuring Molecule in a way it should not be configured.
