### ISSUE TITLE
Using retr0h/molecule doesn't work

### ISSUE THREAD

**Issue by phreddrick** [metacloud/molecule#1430]
# Issue Type

- Bug report

# Molecule and Ansible details

```
docker run --rm -it -v $(pwd):/tmp/$(basename "${PWD}") -w /tmp/$(basename "${PWD}") retr0h/molecule:latest ansible --version
ansible 2.6.1
  config file = None
  configured module search path = [u'/home/molecule/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Dec 14 2017, 15:51:29) [GCC 6.4.0]

```

```
docker run --rm -it -v $(pwd):/tmp/$(basename "${PWD}") -w /tmp/$(basename "${PWD}") retr0h/molecule:latest molecule --version
molecule, version 2.16.0
```

Molecule installation method (one of):

- Using docker container retr0h/molecule

Ansible installation method (one of):

- Using docker container retr0h/molecule

# Desired Behavior

I am fairly new to molecule, so I apologize if I'm missing something obvious.  I'm using the docker version, because I'm trying to setup molecule runs in a gitlab-ci pipeline, and my runner has docker available to it.

Anyway, I'm trying to follow the docker example in the README.md file by running:

```
docker run --rm -it -v $(pwd):/tmp/$(basename "${PWD}") -w /tmp/$(basename "${PWD}") retr0h/molecule:latest molecule init role -r foo -d docker
```
I expect it to create a foo role for me

# Actual Behaviour (Bug report only)

I'm just getting an error saying that README.md doesn't exist.  The output is below.  

```
docker run --rm -it -v $(pwd):/tmp/$(basename "${PWD}") -w /tmp/$(basename "${PWD}") retr0h/molecule:latest molecule init role -r foo -d docker
--> Initializing new role foo...
Traceback (most recent call last):
  File "/usr/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/molecule/command/init/role.py", line 131, in role
    r.execute()
  File "/usr/lib/python2.7/site-packages/molecule/command/init/role.py", line 64, in execute
    self._process_templates('role', self._command_args, role_directory)
  File "/usr/lib/python2.7/site-packages/molecule/command/init/base.py", line 61, in _process_templates
    no_input=True,
  File "/usr/lib/python2.7/site-packages/cookiecutter/main.py", line 94, in cookiecutter
    output_dir=output_dir
  File "/usr/lib/python2.7/site-packages/cookiecutter/generate.py", line 364, in generate_files
    generate_file(project_dir, infile, context, env)
  File "/usr/lib/python2.7/site-packages/cookiecutter/generate.py", line 176, in generate_file
    with io.open(outfile, 'w', encoding='utf-8') as fh:
IOError: [Errno 2] No such file or directory: '/tmp/ansible/foo/README.md'
```
A coworker installed molecule 2.11.0 on a server a little while ago instead of using the docker container, and the init command works fine there.

**Comment by retr0h** [comment]
You might need to run the command again.  I have seen that happen before, and running it again it just works.

**Comment by phreddrick** [comment]
I've run it a number of times, even removed the docker image, and redownloaded it, it always gives me this error.

**Comment by retr0h** [comment]
I can't reproduce, so I cannot really tell you what is going on.

**Comment by phreddrick** [comment]
I think I figured it out, you have to add sudo before the molecule in the original command. So the following works:

```
docker run --rm -it -v $(pwd):/tmp/$(basename "${PWD}") -w /tmp/$(basename "${PWD}") retr0h/molecule:latest sudo molecule init role -r foo -d docker
--> Initializing new role foo...
Initialized role in /tmp/ansible/foo successfully.
```

not sure why since docker is running as root anyway, but this seems to fix it.
