### ISSUE TITLE
rubocop broken on molecule 2.18.0 docker image

### ISSUE THREAD

**Issue by themr0c** [metacloud/molecule#1484]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.6.4
  config file = None
  configured module search path = [u'/home/molecule/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15 (default, Aug 16 2018, 14:17:09) [GCC 6.4.0]
```

```
molecule --version
molecule, version 2.18.0
```

Molecule installation method (one of):

- docker pull retr0h/molecule:latest

Ansible installation method (one of):

- docker pull retr0h/molecule:latest

# Desired Behavior

```
rubocop --version
0.59.1
```

# Actual Behaviour (Bug report only)

```
docker pull retr0h/molecule:latest
latest: Pulling from retr0h/molecule
Digest: sha256:1ef8a8fc4b4ba2aed9c9891785af18f88f0df64f581b3f8db9bce2da87b34f06
Status: Image is up to date for retr0h/molecule:latest

$ docker run -ti retr0h/molecule:latest molecule --version
molecule, version 2.18.0

$ docker run -ti retr0h/molecule:latest rubocop --version
Traceback (most recent call last):
	9: from /usr/bin/rubocop:23:in `<main>'
	8: from /usr/bin/rubocop:23:in `load'
	7: from /usr/lib/ruby/gems/2.5.0/gems/rubocop-0.59.1/exe/rubocop:6:in `<top (required)>'
	6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	4: from /usr/lib/ruby/gems/2.5.0/gems/rubocop-0.59.1/lib/rubocop.rb:634:in `<top (required)>'
	3: from /usr/lib/ruby/gems/2.5.0/gems/rubocop-0.59.1/lib/rubocop.rb:634:in `require_relative'
	2: from /usr/lib/ruby/gems/2.5.0/gems/rubocop-0.59.1/lib/rubocop/result_cache.rb:5:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- etc (LoadError)
```

**Comment by themr0c** [comment]
most probably ruby is causing the issue
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-musl]

On an older version of the docker image, we have same version of rubocop working, but different version of ruby.

```docker run -ti retr0h/molecule@sha256:645e085b6f26b71bf7aa9976a757fb870485bfba47d6d5ae6ec77e45886332e4 bash
bash-4.4$ ruby --version
bash: ruby: command not found
bash-4.4$ sudo apk add  --no-cache curl ruby ruby-dev
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/9) Installing libssh2 (1.8.0-r2)
(2/9) Installing libcurl (7.61.0-r0)
(3/9) Installing curl (7.61.0-r0)
(4/9) Installing yaml (0.1.7-r0)
(5/9) Installing ruby-libs (2.4.4-r0)
(6/9) Installing ruby (2.4.4-r0)
(7/9) Installing libgmpxx (6.1.2-r1)
(8/9) Installing gmp-dev (6.1.2-r1)
(9/9) Installing ruby-dev (2.4.4-r0)
Executing busybox-1.27.2-r7.trigger
OK: 223 MiB in 86 packages
bash-4.4$ ruby --version
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux-musl]
bash-4.4$ sudo gem install --no-rdoc --no-ri rdoc json_pure rubocop
Fetching: rdoc-6.0.4.gem (100%)
Successfully installed rdoc-6.0.4
Fetching: json_pure-2.1.0.gem (100%)
Successfully installed json_pure-2.1.0
Fetching: jaro_winkler-1.5.1.gem (100%)
Building native extensions.  This could take a while...
Successfully installed jaro_winkler-1.5.1
Fetching: parallel-1.12.1.gem (100%)
Successfully installed parallel-1.12.1
Fetching: ast-2.4.0.gem (100%)
Successfully installed ast-2.4.0
Fetching: parser-2.5.1.2.gem (100%)
Successfully installed parser-2.5.1.2
Fetching: powerpack-0.1.2.gem (100%)
Successfully installed powerpack-0.1.2
Fetching: rainbow-3.0.0.gem (100%)
Successfully installed rainbow-3.0.0
Fetching: ruby-progressbar-1.10.0.gem (100%)
Successfully installed ruby-progressbar-1.10.0
Fetching: unicode-display_width-1.4.0.gem (100%)
Successfully installed unicode-display_width-1.4.0
Fetching: rubocop-0.59.1.gem (100%)
Successfully installed rubocop-0.59.1
11 gems installed
bash-4.4$ ruby --version
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux-musl]
bash-4.4$ rubocop --version
0.59.1
```

**Comment by themr0c** [comment]
there was an alpine upgrade in dind: 3.7.0 to 3.8.1

**Comment by themr0c** [comment]
basically, rubocop does not run with ruby 2.5.1-r2 on alpine:3.8, but it still runs well on ruby 2.5.1p57 on debian, so there is probably something fishy specific to this version of alpine.

```docker run -ti  alpine:3.8 sh
/ # apk add  --no-cache curl ruby ruby-dev make gcc libc-dev
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/29) Installing ca-certificates (20171114-r3)
(2/29) Installing nghttp2-libs (1.32.0-r0)
(3/29) Installing libssh2 (1.8.0-r3)
(4/29) Installing libcurl (7.61.1-r0)
(5/29) Installing curl (7.61.1-r0)
(6/29) Installing binutils (2.30-r5)
(7/29) Installing gmp (6.1.2-r1)
(8/29) Installing isl (0.18-r0)
(9/29) Installing libgomp (6.4.0-r8)
(10/29) Installing libatomic (6.4.0-r8)
(11/29) Installing pkgconf (1.5.3-r0)
(12/29) Installing libgcc (6.4.0-r8)
(13/29) Installing mpfr3 (3.1.5-r1)
(14/29) Installing mpc1 (1.0.3-r1)
(15/29) Installing libstdc++ (6.4.0-r8)
(16/29) Installing gcc (6.4.0-r8)
(17/29) Installing musl-dev (1.1.19-r10)
(18/29) Installing libc-dev (0.7.1-r0)
(19/29) Installing make (4.2.1-r2)
(20/29) Installing ncurses-terminfo-base (6.1_p20180818-r1)
(21/29) Installing ncurses-terminfo (6.1_p20180818-r1)
(22/29) Installing ncurses-libs (6.1_p20180818-r1)
(23/29) Installing readline (7.0.003-r0)
(24/29) Installing yaml (0.1.7-r0)
(25/29) Installing ruby-libs (2.5.1-r2)
(26/29) Installing ruby (2.5.1-r2)
(27/29) Installing libgmpxx (6.1.2-r1)
(28/29) Installing gmp-dev (6.1.2-r1)
(29/29) Installing ruby-dev (2.5.1-r2)
Executing busybox-1.28.4-r1.trigger
Executing ca-certificates-20171114-r3.trigger
OK: 122 MiB in 42 packages
/ # gem install --no-rdoc --no-ri rdoc json_pure rubocop
Fetching: rdoc-6.0.4.gem (100%)
Successfully installed rdoc-6.0.4
Fetching: json_pure-2.1.0.gem (100%)
Successfully installed json_pure-2.1.0
Fetching: jaro_winkler-1.5.1.gem (100%)
Building native extensions. This could take a while...
Successfully installed jaro_winkler-1.5.1
Fetching: parallel-1.12.1.gem (100%)
Successfully installed parallel-1.12.1
Fetching: ast-2.4.0.gem (100%)
Successfully installed ast-2.4.0
Fetching: parser-2.5.1.2.gem (100%)
Successfully installed parser-2.5.1.2
Fetching: powerpack-0.1.2.gem (100%)
Successfully installed powerpack-0.1.2
Fetching: rainbow-3.0.0.gem (100%)
Successfully installed rainbow-3.0.0
Fetching: ruby-progressbar-1.10.0.gem (100%)
Successfully installed ruby-progressbar-1.10.0
Fetching: unicode-display_width-1.4.0.gem (100%)
Successfully installed unicode-display_width-1.4.0
Fetching: rubocop-0.59.1.gem (100%)
Successfully installed rubocop-0.59.1
11 gems installed
/ # rubocop --version
Traceback (most recent call last):
	9: from /usr/bin/rubocop:23:in `<main>'
	8: from /usr/bin/rubocop:23:in `load'
	7: from /usr/lib/ruby/gems/2.5.0/gems/rubocop-0.59.1/exe/rubocop:6:in `<top (required)>'
	6: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
	4: from /usr/lib/ruby/gems/2.5.0/gems/rubocop-0.59.1/lib/rubocop.rb:634:in `<top (required)>'
	3: from /usr/lib/ruby/gems/2.5.0/gems/rubocop-0.59.1/lib/rubocop.rb:634:in `require_relative'
	2: from /usr/lib/ruby/gems/2.5.0/gems/rubocop-0.59.1/lib/rubocop/result_cache.rb:5:in `<top (required)>'
	1: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- etc (LoadError)
```

**Comment by themr0c** [comment]
see https://git.alpinelinux.org/cgit/aports/commit/?id=d76cafc1b58d50688d04e15ff1d5be1885ccfd4a

```/ # apk add  --no-cache curl ruby ruby-dev ruby-rdoc make gcc ruby-etc
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz
(1/1) Installing ruby-etc (2.5.1-r2)
OK: 125 MiB in 46 packages
/ # rubocop --version 
0.59.1

**Comment by themr0c** [comment]
We have 2 options now: 
- wait for the fix to propagate from the next release of alpine to docker:dind to molecule 
- add `ruby-etc` to the list pf apk packages to install in the Dockerfile

**Comment by retr0h** [comment]
> add `ruby-etc` to the list pf apk packages to install in the Dockerfile

Sounds like a reasonable fix.  What do you think @themr0c ?

**Comment by retr0h** [comment]
Such a funny error.  I remember way back in the old days of Chef, this was an issue as well lol

**Comment by themr0c** [comment]
@retr0h a funny error indeed. add ruby-etc is indeed the way to have the fix right now.
