### ISSUE TITLE
converge fails on newly init role - python 3.6.6

### ISSUE THREAD

**Issue by drewmullen** [metacloud/molecule#1514]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.7.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/mullendrew/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mullendrew/venv3/lib/python3.6/site-packages/ansible
  executable location = /home/mullendrew/venv3/bin/ansible
  python version = 3.6.6 (default, Jun 27 2018, 14:44:17) [GCC 8.1.0]
```

```
molecule --version
molecule, version 2.18.1
```

Molecule installation method (one of):
- pip

Ansible installation method (one of):
- pip

# Desired Behavior

`molecule test` should complete on a newly init'd role

# Actual Behaviour (Bug report only)

```
python3 -m venv venv
source venv/bin/activate
pip install ansible docker molecule
molecule init role -r my_role -d docker
cd my_role

molecule test
```

`molecule --debug converge` output`
```
    TASK [Gathering Facts] *********************************************************
    task path: /home/mullendrew/my_role/molecule/default/playbook.yml:2
    The full traceback is:
    Traceback (most recent call last):
      File "/home/mullendrew/venv3/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 139, in run
        res = self._execute()
      File "/home/mullendrew/venv3/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 539, in _execute
        self._connection = self._get_connection(variables=variables, templar=templar)
      File "/home/mullendrew/venv3/lib/python3.6/site-packages/ansible/executor/task_executor.py", line 832, in _get_connection
        ansible_playbook_pid=to_text(os.getppid())
      File "/home/mullendrew/venv3/lib/python3.6/site-packages/ansible/plugins/loader.py", line 397, in get
        obj = obj(*args, **kwargs)
      File "/home/mullendrew/venv3/lib/python3.6/site-packages/ansible/plugins/connection/docker.py", line 91, in __init__
        if LooseVersion(docker_version) < LooseVersion(u'1.3'):
      File "/usr/lib/python3.6/distutils/version.py", line 52, in __lt__
        c = self._cmp(other)
      File "/usr/lib/python3.6/distutils/version.py", line 337, in _cmp
        if self.version < other.version:
    TypeError: '<' not supported between instances of 'str' and 'int'
    
    fatal: [instance]: FAILED! => {
        "msg": "Unexpected failure during module execution.",
        "stdout": ""
    }
```

**Comment by drewmullen** [comment]
heres the snippit from /usr/lib/python3.6/distutils/version.py

```
    def _cmp (self, other):
        if isinstance(other, str):
            other = LooseVersion(other)

        if self.version == other.version:
            return 0
        if self.version < other.version:
            return -1
        if self.version > other.version:
            return 1
```

this could actually be an ansible bug. looking for advice on if this should be moved: https://github.com/ansible/ansible/issues/35435

**Comment by sivel** [comment]
It looks like there is an open issue for this specific problem: https://github.com/ansible/ansible/issues/43639
