### ISSUE TITLE
Running tox on master branch throws errors

### ISSUE THREAD

**Issue by sebinjohn** [metacloud/molecule#192]
Getting the below errors on master branch while running tox

Wondering if others also get the same?

```
...
...
nx-rtd-theme==0.1.9,tabulate==0.7.5,testinfra==1.3.0,websocket-client==0.37.0
docs runtests: PYTHONHASHSEED='536444407'
docs runtests: commands[0] | python setup.py build_sphinx
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/Users/sebin/dev/tmp/molecule/.tox/docs/lib/python2.7/site-packages/pbr/core.py", line 111, in pbr
    attrs = util.cfg_to_args(path, dist.script_args)
  File "/Users/sebin/dev/tmp/molecule/.tox/docs/lib/python2.7/site-packages/pbr/util.py", line 246, in cfg_to_args
    pbr.hooks.setup_hook(config)
  File "/Users/sebin/dev/tmp/molecule/.tox/docs/lib/python2.7/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
    metadata_config.run()
  File "/Users/sebin/dev/tmp/molecule/.tox/docs/lib/python2.7/site-packages/pbr/hooks/base.py", line 27, in run
    self.hook()
  File "/Users/sebin/dev/tmp/molecule/.tox/docs/lib/python2.7/site-packages/pbr/hooks/metadata.py", line 26, in hook
    self.config['name'], self.config.get('version', None))
  File "/Users/sebin/dev/tmp/molecule/.tox/docs/lib/python2.7/site-packages/pbr/packaging.py", line 725, in get_version
    raise Exception("Versioning for this project requires either an sdist"
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
error in setup command: Error parsing /Users/sebin/dev/tmp/molecule/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. Are you sure that git is installed?
ERROR: InvocationError: '/Users/sebin/dev/tmp/molecule/.tox/docs/bin/python setup.py build_sphinx'
py27 create: /Users/sebin/dev/tmp/molecule/.tox/py27
py27 installdeps: -rrequirements.txt, -rtest-requirements.txt
py27 inst: /Users/sebin/dev/tmp/molecule/.tox/dist/molecule-1.5.1.zip
...
```

and 

```
....
10,PyYAML==3.11,requests==2.10.0,sh==1.11,six==1.10.0,tabulate==0.7.5,testinfra==1.3.0,testrepository==0.0.20,testtools==2.2.0,tox==2.3.1,traceback2==1.4.0,unittest2==1.1.0,virtualenv==15.0.2,websocket-client==0.37.0,yapf==0.9.0
py27 runtests: PYTHONHASHSEED='536444407'
py27 runtests: commands[0] | python -m unittest discover --failfast
.....................E
======================================================================
ERROR: test_destroy (tests.test_dockerprovisioner.TestDockerProvisioner)
tests.test_dockerprovisioner.TestDockerProvisioner.test_destroy
----------------------------------------------------------------------
_StringException: Traceback (most recent call last):
  File "/Users/sebin/dev/tmp/molecule/tests/test_dockerprovisioner.py", line 100, in test_destroy
    docker_provisioner = provisioners.DockerProvisioner(self._mock_molecule)
  File "/Users/sebin/dev/tmp/molecule/molecule/provisioners.py", line 413, in __init__
    self.status()
  File "/Users/sebin/dev/tmp/molecule/molecule/provisioners.py", line 580, in status
    created_containers = self._docker.containers(all=True)
  File "/Users/sebin/dev/tmp/molecule/.tox/py27/lib/python2.7/site-packages/docker/api/container.py", line 70, in containers
    res = self._result(self._get(u, params=params), True)
  File "/Users/sebin/dev/tmp/molecule/.tox/py27/lib/python2.7/site-packages/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/Users/sebin/dev/tmp/molecule/.tox/py27/lib/python2.7/site-packages/docker/client.py", line 120, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/Users/sebin/dev/tmp/molecule/.tox/py27/lib/python2.7/site-packages/requests/sessions.py", line 487, in get
    return self.request('GET', url, **kwargs)
  File "/Users/sebin/dev/tmp/molecule/.tox/py27/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/sebin/dev/tmp/molecule/.tox/py27/lib/python2.7/site-packages/requests/sessions.py", line 585, in send
    r = adapter.send(request, **kwargs)
  File "/Users/sebin/dev/tmp/molecule/.tox/py27/lib/python2.7/site-packages/requests/adapters.py", line 453, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))


----------------------------------------------------------------------
Ran 22 tests in 0.115s
```

**Comment by kireledan** [comment]
Interesting - my fork is even with master at the moment and the travis build seems to be running fine. First error looks like its complaining that git isn't installed? And with the second one - are any of the other docker tests passing for you?

**Comment by sebinjohn** [comment]
I am on OSX Capitan and I use docker-toolbox to setup docker

For the second issue, I did the following

without setting any docker parameters, execute the unittest manually.

`pwd && python -m unittest discover --failfast`

Result  is 
```
/Users/sebin/dev/molecule
.....................E
======================================================================
ERROR: test_destroy (tests.test_dockerprovisioner.TestDockerProvisioner)
tests.test_dockerprovisioner.TestDockerProvisioner.test_destroy
----------------------------------------------------------------------
_StringException: Traceback (most recent call last):
  File "/Users/sebin/dev/molecule/tests/test_dockerprovisioner.py", line 100, in test_destroy
    docker_provisioner = provisioners.DockerProvisioner(self._mock_molecule)
  File "/Users/sebin/dev/molecule/molecule/provisioners.py", line 413, in __init__
    self.status()
  File "/Users/sebin/dev/molecule/molecule/provisioners.py", line 580, in status
    created_containers = self._docker.containers(all=True)
  File "/usr/local/lib/python2.7/site-packages/docker_py-1.8.0-py2.7.egg/docker/api/container.py", line 70, in containers
    res = self._result(self._get(u, params=params), True)
  File "/usr/local/lib/python2.7/site-packages/docker_py-1.8.0-py2.7.egg/docker/utils/decorators.py", line 47, in inner
    return f(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/docker_py-1.8.0-py2.7.egg/docker/client.py", line 120, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "/usr/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 477, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/requests-2.7.0-py2.7.egg/requests/adapters.py", line 415, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', error(2, 'No such file or directory'))


----------------------------------------------------------------------
Ran 22 tests in 0.109s

FAILED (errors=1)
```

now if I set docker parameters using `eval $(docker-machine env docker)` and rerun the unittest

`pwd && python -m unittest discover --failfast`

Result is:

```
pwd && python -m unittest discover --failfast
/Users/sebin/dev/molecule
..................... Creating container test1 with base image ubuntu:latest ...  Container created.

 Creating container test2 with base image ubuntu:latest ...  Container created.

 Stopping container test1 ...  Removed container test1.

 Stopping container test2 ...  Removed container test2.

... Creating container test1 with base image ubuntu:latest ...  Container created.

 Creating container test2 with base image ubuntu:latest ...  Container created.

...

test1                      : ok=2    changed=1    unreachable=0    failed=0
test2                      : ok=2    changed=1    unreachable=0    failed=0

. Starting container  ...
 Starting container  ...
. Starting container  ...
 Starting container  ...
 Stopping container test1 ...  Removed container test1.

 Stopping container test2 ...  Removed container test2.

.........................
----------------------------------------------------------------------
Ran 53 tests in 11.331s

OK

```

So, I think when tox runs the test docker environment variables are somehow ignored.

**Comment by kireledan** [comment]
The docker environment variables aren't being ignored. From what you describe it looks like you just didn't have them set. The docker provisioner will only read from your current variables. It won't search your machines to set them. Also you should give the new docker beta a try - It's really awesome because you can use docker without having to set up a docker-machine.

**Comment by sebinjohn** [comment]
@kireledan apologies if I sound confusing.
What I have tried to explain is that if I set docker parameters and run unittest manually(`python -m unittest discover --failfast`) it will work and the same doesn't work when I use tox.

So, I just made a change - https://github.com/sebinjohn/molecule/commit/03f52daf1bd1e6940940dc968472d35f44c45087 to the`tox.ini`

and now the tests work fine.

Also, I have signed up a while back for the docker for mac beta program. Still waiting for it. :)

**Comment by kireledan** [comment]
Ahhh I see what you mean now. Makes sense - no worries! 

It's open beta now actually as of yesterday.  https://www.docker.com/products/docker#/mac

**Comment by sebinjohn** [comment]
@kireledan Thanks. I installed it.

**Comment by retr0h** [comment]
@sebinjohn is this issue resolved?

**Comment by kireledan** [comment]
Their PR has the change they made to fix the tox tests. I'd imagine this issue is safe to close.

**Comment by retr0h** [comment]
@kireledan good call.  Closing.  @sebinjohn please re-open if still an issue.

**Comment by sebinjohn** [comment]
👍
