### ISSUE TITLE
molecule init doesn't create tests directory

### ISSUE THREAD

**Issue by alop** [metacloud/molecule#259]
```
molecule init alop.test
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/Users/abelopez/Library/Python/2.7/lib/python/site-packages/molecule/cli.py", line 69, in main
    CLI().main()
  File "/Users/abelopez/Library/Python/2.7/lib/python/site-packages/molecule/cli.py", line 65, in main
    sys.exit(c.execute()[0])
  File "/Users/abelopez/Library/Python/2.7/lib/python/site-packages/molecule/commands.py", line 792, in execute
    with open(os.path.join(testinfra_path, 'test_default.py'), 'w') as f:
IOError: [Errno 2] No such file or directory: './alop.test/tests/test_default.py'
```

**Comment by kireledan** [comment]
I am unable to re-create this. What version are you running?

**Comment by alop** [comment]
molecule -v
1.7.0

**Comment by kireledan** [comment]
Odd. I've tried creating a new environment and installing from pip and also checked out the 1.7 branch. I'm still unable to recreate this error. I'll go ahead and add a check for the directory before making the test defaults to ensure this error does not pop up again for you in later versions.

**Comment by alop** [comment]
no, looks like it was my env.

**Comment by retr0h** [comment]
Readdressed by #261.
