### ISSUE TITLE
Molecule commands are broken when specifying an ansible.cfg file

### ISSUE THREAD

**Issue by abrown-sg** [metacloud/molecule#284]
When attempting to do a `molecule destroy` in a role where molecule.yml points to a custom location for ansible.cfg, the following error is produced:

```
molecule destroy
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 10, in <module>
    sys.exit(main())
  File "/Users/abrown/projects/cisco/molecule/molecule/cli.py", line 68, in main
    CLI().main()
  File "/Users/abrown/projects/cisco/molecule/molecule/cli.py", line 64, in main
    utilities.sysexit(c.execute()[0])
  File "/Users/abrown/projects/cisco/molecule/molecule/commands/destroy.py", line 47, in execute
    self.molecule._create_templates()
  File "/Users/abrown/projects/cisco/molecule/molecule/core.py", line 197, in _create_templates
    self._config.config['ansible']['config_file'], kwargs=kwargs)
  File "/Users/abrown/projects/cisco/molecule/molecule/utilities.py", line 104, in write_template
    with open(dest, 'w') as f:
IOError: [Errno 2] No such file or directory: '.molecule/../../.molecule/ansible.cfg'
```

The relevant values in molecule.yml are:

```
ansible:
  config_file: ../../.molecule/ansible.cfg
```

**Comment by retr0h** [comment]
It's simply relative to the `molecule_dir`.

Works as expected if changing to

```
ansible:
  config_file: ../../../.molecule/ansible.cfg
```
