### ISSUE TITLE
Fedora 24 support

### ISSUE THREAD

**Issue by kostyrevaa** [metacloud/molecule#317]
with `1.8.3` I can't use Fedora 24 as a target platform.
It blows with:
```
Creating container koji-client-fedora24 with base image fedora:24 ...
Traceback (most recent call last):
  File "/usr/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/molecule/cli.py", line 68, in main
    CLI().main()
  File "/usr/lib/python2.7/site-packages/molecule/cli.py", line 64, in main
    utilities.sysexit(c.execute()[0])
  File "/usr/lib/python2.7/site-packages/molecule/commands/create.py", line 48, in execute
    self.molecule._provisioner.up(no_provision=True)
  File "/usr/lib/python2.7/site-packages/molecule/provisioners/dockerprovisioner.py", line 188, in up
    host_config=docker_host_config)
  File "/usr/lib/python2.7/site-packages/docker/api/container.py", line 120, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/lib/python2.7/site-packages/docker/api/container.py", line 131, in create_container_from_config
    return self._result(res, True)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 178, in _result
    self._raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("No command specified")
```
`molecule.yml`:
```
docker:
  containers:
    - name: koji-client-fedora24
      ansible_groups:
        - koji_client
      image: fedora
      image_version: 24
```
`docker -v`
```
Docker version 1.10.3, build 29066b4/1.10.3
```

**Comment by retr0h** [comment]
Looks like that container wasn't baked with a command to execute.  On the master version of molecule you can update your `molecule.yml` with a `command`.

See our [docs](http://molecule.readthedocs.io/en/latest/provisioners.html?highlight=docker#docker-example).

**Comment by kostyrevaa** [comment]
So to use molecule in Travis I need to install it from [source](http://molecule.readthedocs.io/en/latest/usage.html#installing-from-source) onto travis vm?

**Comment by retr0h** [comment]
> So to use molecule in Travis I need to install it from source onto travis vm?

Until we release molecule `1.9` to pypi.

**Comment by retr0h** [comment]
Closing.  Already fixed.
