### ISSUE TITLE
1.9.0: sh.CommandNotFound: ansible_galaxy

### ISSUE THREAD

**Issue by dj-wasabi** [metacloud/molecule#394]
Hi,

A test on Travis installed version 1.9.0  (https://travis-ci.org/dj-wasabi/ansible-zabbix-proxy/builds/154438070) and it fails when it tries to download the dependencies.

```
--> Installing role dependencies ...
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.10/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/molecule/cli.py", line 68, in main
    CLI().main()
  File "/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/molecule/cli.py", line 64, in main
    util.sysexit(c.execute()[0])
  File "/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/molecule/command/test.py", line 57, in execute
    status, output = c.execute(exit=False)
  File "/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/molecule/command/converge.py", line 86, in execute
    galaxy.install()
  File "/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/molecule/ansible_galaxy.py", line 102, in install
    self.bake()
  File "/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/molecule/ansible_galaxy.py", line 68, in bake
    self._galaxy = sh.ansible_galaxy.bake('install',
  File "/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/sh.py", line 2301, in __getattr__
    return self.__env[name]
  File "/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/sh.py", line 2232, in __getitem__
    return Command._create(k, **self.baked_args)
  File "/home/travis/virtualenv/python2.7.10/lib/python2.7/site-packages/sh.py", line 776, in _create
    raise CommandNotFound(program)
sh.CommandNotFound: ansible_galaxy
```

I don't see on the documentation that ansible-galaxy needs to be installed separately?

Kind regards,
Werner

**Comment by retr0h** [comment]
Hi @dj-wasabi molecule no longer installs ansible through it's requirements.  We assume people want to control the version of ansible they are running.

I noticed your [travis file](https://github.com/dj-wasabi/ansible-zabbix-proxy/blob/molecule_test/.travis.yml#L12) doesn't install ansible.  You should be good if you install ansible before molecule.

**Comment by dj-wasabi** [comment]
Ok, thanks! Will make sure I install it within the .travis.yml file.
