### ISSUE TITLE
Molecule create throws error using Docker on macOS

### ISSUE THREAD

**Issue by yveslaroche** [metacloud/molecule#489]
Using:
- Python 2.7.12
- Molecule 1.11.0
- Docker 1.12.1 (Docker for Mac)

```sh
❯ molecule init foo --docker && cd foo
--> Initializing role foo...
Successfully initialized new role in /Users/yves.laroche/Desktop/foo...

~/Desktop/foo
❯ molecule create
--> Creating instances ...
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/molecule/cli.py", line 68, in main
    CLI().main()
  File "/usr/local/lib/python2.7/site-packages/molecule/cli.py", line 64, in main
    util.sysexit(c.execute()[0])
  File "/usr/local/lib/python2.7/site-packages/molecule/command/create.py", line 55, in execute
    self.molecule.driver.up(no_provision=True)
  File "/usr/local/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 113, in up
    self._build_ansible_compatible_image()
  File "/usr/local/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 216, in _build_ansible_compatible_image
    for tag in image.get('RepoTags')]
TypeError: 'NoneType' object is not iterable
```

**Comment by retr0h** [comment]
What version of docker-py is installed on your system?  I can't reproduce this issue.

```
[jodewey:~/git/molecule]+ ± pip freeze | grep docker-py
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by yveslaroche** [comment]
```sh
❯  pip freeze | grep docker-py
docker-py==1.9.0
docker-pycreds==0.2.1
```

**Comment by retr0h** [comment]
I can't reproduce.  I've nuked my docker data dir too (~/Library/Containers/com.docker.docker/Data/).

If you modify the following does that solve the problem?  I can submit a hotfix if it does.

`/usr/local/lib/python2.7/site-packages/molecule/driver/dockerdriver.py` 

from 

`for tag in image.get('RepoTags')]`

to

`for tag in image.get('RepoTags', [])]`

**Comment by yveslaroche** [comment]
I get the same problem.
```
❯ molecule create
--> Creating instances ...
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/molecule/cli.py", line 68, in main
    CLI().main()
  File "/usr/local/lib/python2.7/site-packages/molecule/cli.py", line 64, in main
    util.sysexit(c.execute()[0])
  File "/usr/local/lib/python2.7/site-packages/molecule/command/create.py", line 55, in execute
    self.molecule.driver.up(no_provision=True)
  File "/usr/local/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 113, in up
    self._build_ansible_compatible_image()
  File "/usr/local/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 216, in _build_ansible_compatible_image
    for tag in image.get('RepoTags', [])]
TypeError: 'NoneType' object is not iterable
```

**Comment by yveslaroche** [comment]
Thanks, I have deleted my Docker data dir and it is working now.

**Comment by retr0h** [comment]
👍 🎸

**Comment by dbryant4** [comment]
I deleted any image which showed `<none>` in either the repository or tag column of `docker images` output to get around this issue
