### ISSUE TITLE
Using "--platform" argument fails in 1.11.0

### ISSUE THREAD

**Issue by techraf** [metacloud/molecule#490]
Whenever a `--platform` argument is added, Molecule 1.11.0 seems to fail:

```
# molecule create --platform osx
--> Creating instances ...
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/molecule/cli.py", line 68, in main
    CLI().main()
  File "/usr/local/lib/python2.7/site-packages/molecule/cli.py", line 64, in main
    util.sysexit(c.execute()[0])
  File "/usr/local/lib/python2.7/site-packages/molecule/command/create.py", line 55, in execute
    self.molecule.driver.up(no_provision=True)
  File "/usr/local/lib/python2.7/site-packages/molecule/driver/vagrantdriver.py", line 131, in up
    self._populate_platform_instances()
  File "/usr/local/lib/python2.7/site-packages/molecule/driver/vagrantdriver.py", line 190, in _populate_platform_instances
    1) and (self.molecule.args['--platform'] == 'all'
TypeError: object of type 'bool' has no len()
```

**Comment by retr0h** [comment]
Hi @techraf Can you please provide your `molecule.yml`.

**Comment by retr0h** [comment]
Confirmed patch on the way.

**Comment by retr0h** [comment]
@techraf thanks for your report.  Have pushed molecule 1.11.1 to pypi with the fix.
