### ISSUE TITLE
Skipping due to errors during converge.

### ISSUE THREAD

**Issue by skitoo** [metacloud/molecule#495]
Hello,

I install a package via pip. And after that, I have this error during idempotence test: "Skipping due to errors during converge."

You can check my code and show test results in my MR : https://github.com/skitoo/bender/pull/5

How can I solve this problem ? 

Thank you.

**Comment by retr0h** [comment]
Hi @skitoo.

If you re-run `molecule converge` it looks like a problem with your python-docker task.  The idempotence check simply runs a converge again, hiding stdout/err and making sure changed=0.

```
TASK [docker : Install python-docker] ******************************************
fatal: [bender]: FAILED! => {"changed": false, "cmd": "/usr/bin/pip install docker-py==1.7.0", "failed": true, "msg": "\n:stderr: Traceback (most recent call last):\n  File \"/usr/bin/pip\", line 9, in <module>\n    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources.py\", line 356, in load_entry_point\n    return get_distribution(dist).load_entry_point(group, name)\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources.py\", line 2476, in load_entry_point\n    return ep.load()\n  File \"/usr/lib/python2.7/dist-packages/pkg_resources.py\", line 2190, in load\n    ['__name__'])\n  File \"/usr/lib/python2.7/dist-packages/pip/__init__.py\", line 74, in <module>\n    from pip.vcs import git, mercurial, subversion, bazaar  # noqa\n  File \"/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py\", line 9, in <module>\n    from pip.download import path_to_url\n  File \"/usr/lib/python2.7/dist-packages/pip/download.py\", line 25, in <module>\n    from requests.compat import IncompleteRead\nImportError: cannot import name IncompleteRead\n"}
```

**Comment by retr0h** [comment]
Not sure how you wish to correct the problem, but I was able to [correct it](https://github.com/donovan6000/M33-Fio/issues/147).


```
root@75fdb5a89d6d:/# pip --version
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    load_entry_point('pip==1.5.6', 'console_scripts', 'pip')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/lib/python2.7/dist-packages/pip/__init__.py", line 74, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/lib/python2.7/dist-packages/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 25, in <module>
    from requests.compat import IncompleteRead
ImportError: cannot import name IncompleteRead
root@75fdb5a89d6d:/# python --version
Python 2.7.9
root@75fdb5a89d6d:/# sudo rm -rf /usr/local/lib/python2.7/dist-packages/requests*

root@75fdb5a89d6d:/# pip --version
pip 1.5.6 from /usr/lib/python2.7/dist-packages (python 2.7)
```

**Comment by retr0h** [comment]
@skitoo get this sorted?

**Comment by retr0h** [comment]
@skitoo I am closing this issue.  Please re-open if this is not sorted.  I should have provided enough details as to why it is failing above.
