### ISSUE TITLE
Ubuntu 14.04 Molecule `pip` install errors out of box

### ISSUE THREAD

**Issue by conatus** [metacloud/molecule#498]
Hi all,

Thanks for your work on this and in advance for your help.

I have installed (using Ansible) the latest molecule on our GitLab runners.

Just running the molecule command with any switch and as any user appears to fail. The `cryptography` package is missing, which is fine, I installed this. Even after fixing this, `shade`, the OpenStack driver, appears to be broken. However, `shade` is successfully installed at the version required by Molecule.

Any clues to what is going on?

Full transcript:

```
gitlab-runner@gitlab-runner:~/builds/e17efd0c/0/now/underscore-config$ molecule
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 7, in <module>
    from molecule.cli import main
  File "/usr/local/lib/python2.7/dist-packages/molecule/cli.py", line 46, in <module>
    from molecule import command
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/__init__.py", line 25, in <module>
    from molecule.command import base  # noqa
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/base.py", line 24, in <module>
    from molecule import core
  File "/usr/local/lib/python2.7/dist-packages/molecule/core.py", line 32, in <module>
    from molecule.driver import openstackdriver
  File "/usr/local/lib/python2.7/dist-packages/molecule/driver/openstackdriver.py", line 28, in <module>
    import paramiko
  File "/usr/local/lib/python2.7/dist-packages/paramiko/__init__.py", line 30, in <module>
    from paramiko.transport import SecurityOptions, Transport
  File "/usr/local/lib/python2.7/dist-packages/paramiko/transport.py", line 32, in <module>
    from cryptography.hazmat.backends import default_backend
ImportError: No module named cryptography.hazmat.backends
gitlab-runner@gitlab-runner:~/builds/e17efd0c/0/now/underscore-config$ exit
< snip>
root@gitlab-runner:~# apt install libffi-dev && pip install cryptography
< snip >
gitlab-runner@gitlab-runner:~$ molecule
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 7, in <module>
    from molecule.cli import main
  File "/usr/local/lib/python2.7/dist-packages/molecule/cli.py", line 46, in <module>
    from molecule import command
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/__init__.py", line 25, in <module>
    from molecule.command import base  # noqa
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/base.py", line 24, in <module>
    from molecule import core
  File "/usr/local/lib/python2.7/dist-packages/molecule/core.py", line 32, in <module>
    from molecule.driver import openstackdriver
  File "/usr/local/lib/python2.7/dist-packages/molecule/driver/openstackdriver.py", line 29, in <module>
    import shade
  File "/usr/local/lib/python2.7/dist-packages/shade/__init__.py", line 18, in <module>
    import keystoneauth1.exceptions
ImportError: No module named keystoneauth1.exceptions
gitlab-runner@gitlab-runner:~$ python --version
Python 2.7.6
<snip>
root@gitlab-runner:~# pip install shade==1.11.1
Requirement already satisfied (use --upgrade to upgrade): shade==1.11.1 in /usr/local/lib/python2.7/dist-packages
Cleaning up...
root@gitlab-runner:~# molecule -h
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 7, in <module>
    from molecule.cli import main
  File "/usr/local/lib/python2.7/dist-packages/molecule/cli.py", line 46, in <module>
    from molecule import command
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/__init__.py", line 25, in <module>
    from molecule.command import base  # noqa
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/base.py", line 24, in <module>
    from molecule import core
  File "/usr/local/lib/python2.7/dist-packages/molecule/core.py", line 32, in <module>
    from molecule.driver import openstackdriver
  File "/usr/local/lib/python2.7/dist-packages/molecule/driver/openstackdriver.py", line 29, in <module>
    import shade
  File "/usr/local/lib/python2.7/dist-packages/shade/__init__.py", line 18, in <module>
    import keystoneauth1.exceptions
ImportError: No module named keystoneauth1.exceptions
```

**Comment by retr0h** [comment]
Do you have these packages installed?

```
[jodewey:~/git/molecule] master+ ± pip freeze | grep keystone
keystoneauth1==2.12.1
python-keystoneclient==3.3.0
```

**Comment by conatus** [comment]
Thanks very much. 

No I don't have either dependency and they don't install either. 

```
root@gitlab-runner:~# pip install keystoneauth1==2.12.1
Downloading/unpacking keystoneauth1==2.12.1
  Downloading keystoneauth1-2.12.1-py2.py3-none-any.whl (232kB): 232kB downloaded
Requirement already satisfied (use --upgrade to upgrade): requests>=2.10.0 in /usr/local/lib/python2.7/dist-packages (from keystoneauth1==2.12.1)
Downloading/unpacking six>=1.9.0 (from keystoneauth1==2.12.1)
  Downloading six-1.10.0-py2.py3-none-any.whl
Downloading/unpacking iso8601>=0.1.11 (from keystoneauth1==2.12.1)
  Downloading iso8601-0.1.11-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): pbr>=1.6 in /usr/local/lib/python2.7/dist-packages (from keystoneauth1==2.12.1)
Downloading/unpacking stevedore>=1.16.0 (from keystoneauth1==2.12.1)
  Downloading stevedore-1.17.1-py2.py3-none-any.whl
Downloading/unpacking positional>=1.0.1 (from keystoneauth1==2.12.1)
  Downloading positional-1.1.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/positional/setup.py) egg_info for package positional
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/pbr/core.py", line 111, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/usr/local/lib/python2.7/dist-packages/pbr/util.py", line 264, in cfg_to_args
        wrap_commands(kwargs)
      File "/usr/local/lib/python2.7/dist-packages/pbr/util.py", line 566, in wrap_commands
        cmdclass = ep.resolve()
      File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2264, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/local/lib/python2.7/dist-packages/flake8/main/setuptools_command.py", line 6, in <module>
        from flake8.main import application as app
      File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 14, in <module>
        from flake8.main import options
      File "/usr/local/lib/python2.7/dist-packages/flake8/main/options.py", line 3, in <module>
        from flake8.main import vcs
      File "/usr/local/lib/python2.7/dist-packages/flake8/main/vcs.py", line 4, in <module>
        from flake8.main import mercurial
      File "/usr/local/lib/python2.7/dist-packages/flake8/main/mercurial.py", line 7, in <module>
        import configparser
    ImportError: No module named configparser
    error in setup command: Error parsing /tmp/pip_build_root/positional/setup.cfg: ImportError: No module named configparser
    Complete output from command python setup.py egg_info:
    ERROR:root:Error parsing

Traceback (most recent call last):

  File "/usr/local/lib/python2.7/dist-packages/pbr/core.py", line 111, in pbr

    attrs = util.cfg_to_args(path, dist.script_args)

  File "/usr/local/lib/python2.7/dist-packages/pbr/util.py", line 264, in cfg_to_args

    wrap_commands(kwargs)

  File "/usr/local/lib/python2.7/dist-packages/pbr/util.py", line 566, in wrap_commands

    cmdclass = ep.resolve()

  File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2264, in resolve

    module = __import__(self.module_name, fromlist=['__name__'], level=0)

  File "/usr/local/lib/python2.7/dist-packages/flake8/main/setuptools_command.py", line 6, in <module>

    from flake8.main import application as app

  File "/usr/local/lib/python2.7/dist-packages/flake8/main/application.py", line 14, in <module>

    from flake8.main import options

  File "/usr/local/lib/python2.7/dist-packages/flake8/main/options.py", line 3, in <module>

    from flake8.main import vcs

  File "/usr/local/lib/python2.7/dist-packages/flake8/main/vcs.py", line 4, in <module>

    from flake8.main import mercurial

  File "/usr/local/lib/python2.7/dist-packages/flake8/main/mercurial.py", line 7, in <module>

    import configparser

ImportError: No module named configparser

error in setup command: Error parsing /tmp/pip_build_root/positional/setup.cfg: ImportError: No module named configparser

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/positional
Storing debug log for failure in /home/ubuntu/.pip/pip.log
```

`pip install python-keystoneclient==3.3.0` fails similarly. As I'm sure you are aware `configparser` is what `ConfigParser` is called in the world of Python 3, which seems a little odd because I am explicitly on 2.7 series here.

**Comment by conatus** [comment]
So, I installed the following packages manually:
  - pytz
  - iso8601
  - cryptography
  - os-client-config
  - dogpile
  - dogpile.cache
  - python-cinderclient
  - python-glanceclient
  - python-heatclient
  - python-magnumclient
  - python-neutronclient
  - python-novaclient
  - python-troveclient
  - python-designateclient
  - python-ironicclient
  - munch
  - poyo
  - click
  - future
  - binaryornot
  - whichcraft

And it appears to now work but only by pinning the version of Molecule to 1.1.1. It seems the problem is Shade, proving the OpenStack support, doesn't bring in its dependencies in the way you would expect it to. Thus a lot of stuff is missing.

I am looking into what is happening with the very latest release of Molecule but problem appears roughly similar.

This is stock Ubuntu 14.04 by the way, official AWS AMIs or Vagrant boxes.

**Comment by conatus** [comment]
Seem this manual installation was necessary due to a broken and aborted `pip install molecule` at the top of the process, which failed due to failing to compile C extensions - all initially done with Ansible. I'll track down the precise reasons for this incomplete installation and add any additional dependencies (say header files for C extensions).

Thanks.
