### ISSUE TITLE
"No command specified" when trying to test a role on Suse

### ISSUE THREAD

**Issue by dj-wasabi** [metacloud/molecule#513]
Hi,

I need to test a role on Suse and I get an error message when i do a `molecule create`:
```
	Successfully built dcc238ecad79
Finished building molecule_local/opensuse:latest
Creating container zabbix-agent-suse with base image opensuse:latest ...
Creating container zabbix-agent-suse with base image opensuse:latest ...
Traceback (most recent call last):
  File "/usr/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/molecule/cli.py", line 68, in main
    CLI().main()
  File "/usr/lib/python2.7/site-packages/molecule/cli.py", line 64, in main
    util.sysexit(c.execute()[0])
  File "/usr/lib/python2.7/site-packages/molecule/command/create.py", line 55, in execute
    self.molecule.driver.up(no_provision=True)
  File "/usr/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 148, in up
    command=container['command'])
  File "/usr/lib/python2.7/site-packages/docker/api/container.py", line 120, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/lib/python2.7/site-packages/docker/api/container.py", line 131, in create_container_from_config
    return self._result(res, True)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 178, in _result
    self._raise_for_status(response)
  File "/usr/lib/python2.7/site-packages/docker/client.py", line 174, in _raise_for_status
    raise errors.APIError(e, response, explanation=explanation)
docker.errors.APIError: 400 Client Error: Bad Request ("{"message":"No command specified"}")
```
My configuration:
_molecule.yml_
```
docker:
  containers:
  - name: zabbix-agent-suse
    ansible_groups:
      - group3
    image: opensuse
    image_version: latest
    privileged: True
```

I've updated locally the file `driver/dockerdriver.py` by adding the following line (234):
```
RUN bash -c 'if [ -x "$(command -v zypper)" ]; then zypper install -y python sudo; fi'
```
So python and sudo are installed in the new molecule container, but don't know **yet** how to continue. Otherwise I would have created a pr.

```
_$ molecule --version
1.11.4
```

Any idea?

**Comment by retr0h** [comment]
> docker.errors.APIError: 400 Client Error: Bad Request ("{"message":"No command specified"}")

Hi @dj-wasabi, the error is telling you to specify a command for the container to run.

Some containers are baked with a command to run when the container is executed, others are not.  The `opensuse` container you are using does not have a command so it exits.

Your molecule.yml should contain a command.
```

docker:
  containers:
  - name: zabbix-agent-suse
    ansible_groups:
      - group3
    image: opensuse
    image_version: latest
    privileged: True
    command: /bin/bash # arbitrary command
```

**Comment by retr0h** [comment]
> RUN bash -c 'if [ -x "$(command -v zypper)" ]; then zypper install -y python sudo; fi'

This is a valid bug, and would appreciate a PR.
