### ISSUE TITLE
Idempotence edge case

### ISSUE THREAD

**Issue by retr0h** [metacloud/molecule#554]
```
+ molecule idempotence
--> Idempotence test in progress (can take a few minutes) ...
--> Starting Ansible Run ...
Idempotence test failed because of the following tasks:
Traceback (most recent call last):
  File "/home/leeroy-jenkins/jenkins/workspace/ci-molecule-ansible-systems-cisco.metapod_common/venv/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/home/leeroy-jenkins/jenkins/workspace/ci-molecule-ansible-systems-cisco.metapod_common/venv/lib/python2.7/site-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/home/leeroy-jenkins/jenkins/workspace/ci-molecule-ansible-systems-cisco.metapod_common/venv/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/leeroy-jenkins/jenkins/workspace/ci-molecule-ansible-systems-cisco.metapod_common/venv/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/leeroy-jenkins/jenkins/workspace/ci-molecule-ansible-systems-cisco.metapod_common/venv/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/leeroy-jenkins/jenkins/workspace/ci-molecule-ansible-systems-cisco.metapod_common/venv/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/leeroy-jenkins/jenkins/workspace/ci-molecule-ansible-systems-cisco.metapod_common/venv/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/leeroy-jenkins/jenkins/workspace/ci-molecule-ansible-systems-cisco.metapod_common/venv/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/leeroy-jenkins/jenkins/workspace/ci-molecule-ansible-systems-cisco.metapod_common/venv/lib/python2.7/site-packages/molecule/command/idempotence.py", line 119, in idempotence
    util.sysexit(i.execute()[0])
  File "/home/leeroy-jenkins/jenkins/workspace/ci-molecule-ansible-systems-cisco.metapod_common/venv/lib/python2.7/site-packages/molecule/command/idempotence.py", line 61, in execute
    LOG.error('\n'.join(self._non_idempotent_tasks(output)))
  File "/home/leeroy-jenkins/jenkins/workspace/ci-molecule-ansible-systems-cisco.metapod_common/venv/lib/python2.7/site-packages/molecule/command/idempotence.py", line 104, in _non_idempotent_tasks
    res.append('* {}'.format(task_name.groups()[0]))
AttributeError: 'NoneType' object has no attribute 'groups'
```

**Comment by retr0h** [comment]
Released fix to pypi as 1.12.6.
