### ISSUE TITLE
Cookiecutter errors

### ISSUE THREAD

**Issue by johnsiciliano** [metacloud/molecule#594]
$ molecule init
--> Initializing molecule in current directory ...
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/init.py", line 137, in init
    util.sysexit(i.execute()[0])
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/init.py", line 55, in execute
    self._init_existing_role(role, role_path, driver, verifier)
  File "/usr/local/lib/python2.7/dist-packages/molecule/command/init.py", line 72, in _init_existing_role
    util.process_templates(template, extra_context, role_path)
  File "/usr/local/lib/python2.7/dist-packages/molecule/util.py", line 165, in process_templates
    no_input=True, )
  File "/usr/local/lib/python2.7/dist-packages/molecule/cookiecutter/main.py", line 116, in cookiecutter
    'The repository {0} could not be located.'.format(template)
molecule.cookiecutter.exceptions.RepositoryNotFound: The repository /usr/local/lib/python2.7/dist-packages/molecule/cookiecutter/playbook could not be located.

This started happening recently.
I attempted removing Ubuntu cookiecutter, using pip -r on requirements.txt on the newest release version of molecule and the problem persists.

Am i missing something?

**Comment by retr0h** [comment]
What version of molecule?

**Comment by johnsiciliano** [comment]
john@johns-probook:~/Downloads/molecule-1.13$ sudo !!
sudo python setup.py install
running install
running build
running build_py
running egg_info
writing requirements to molecule.egg-info/requires.txt
writing molecule.egg-info/PKG-INFO
writing top-level names to molecule.egg-info/top_level.txt
writing dependency_links to molecule.egg-info/dependency_links.txt
writing entry points to molecule.egg-info/entry_points.txt
writing pbr to molecule.egg-info/pbr.json
[pbr] Reusing existing SOURCES.txt
running install_lib
running install_data
running install_egg_info
removing '/usr/local/lib/python2.7/dist-packages/molecule-0.0.1.dev1.egg-info' (and everything under it)
Copying molecule.egg-info to /usr/local/lib/python2.7/dist-packages/molecule-0.0.1.dev1.egg-info
running install_scripts
Installing molecule script to /usr/local/bin
john@johns-probook:~/Downloads/molecule-1.13$ molecule --version
molecule, version 0.0.1.dev1
john@johns-probook:~/Downloads/molecule-1.13$ whereis molecule
molecule: /usr/local/bin/molecule

**Comment by retr0h** [comment]
> john@johns-probook:~/Downloads/molecule-1.13$ molecule --version
> molecule, version 0.0.1.dev1

That molecule version looks wrong.  Try installing from pip and not source.

**Comment by johnsiciliano** [comment]
Thanks this works
