### ISSUE TITLE
Text encoding error on certain `--diff` output

### ISSUE THREAD

**Issue by conorsch** [metacloud/molecule#727]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
$ molecule --version
molecule, version 1.17.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

When applying a role that contains strings such as ``0x`` in a template with `diff: yes` (the default), Molecule displays the diff intelligently and continues merrily along with execution of the playbook.

# Actual Behaviour (Bug report only)

When applying a role that contains strings such as ``0x`` in a template with `diff: yes` (the default), Molecule loses its mind and throws a stack trace to the screen, aborting the play but hanging on the invocation until `ctrl+c` is entered to return to the calling console:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/conor/gits/molecule-diff-encoding-bug/venv/local/lib/python2.7/site-packages/sh.py", line 1484, in output_thread
    done = stream.read()
  File "/home/conor/gits/molecule-diff-encoding-bug/venv/local/lib/python2.7/site-packages/sh.py", line 1974, in read
    self.write_chunk(chunk)
  File "/home/conor/gits/molecule-diff-encoding-bug/venv/local/lib/python2.7/site-packages/sh.py", line 1949, in write_chunk
    self.should_quit = self.process_chunk(chunk)
  File "/home/conor/gits/molecule-diff-encoding-bug/venv/local/lib/python2.7/site-packages/sh.py", line 1867, in process
    return handler(chunk)
  File "/home/conor/gits/molecule-diff-encoding-bug/venv/local/lib/python2.7/site-packages/sh.py", line 1106, in fn
    return handler(chunk, *args)
  File "/home/conor/gits/molecule-diff-encoding-bug/venv/local/lib/python2.7/site-packages/molecule/util.py", line 81, in callback_info
    print_info(msg, pretty=False)
  File "/home/conor/gits/molecule-diff-encoding-bug/venv/local/lib/python2.7/site-packages/molecule/util.py", line 45, in print_info
    print_msg('{}', msg)
  File "/home/conor/gits/molecule-diff-encoding-bug/venv/local/lib/python2.7/site-packages/molecule/util.py", line 76, in print_msg
    print(template.format(msg.rstrip()))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb4' in position 57: ordinal not in range(128)
```
Here is a reproducible test in an isolated repo to aid in debugging: https://github.com/conorsch/molecule-diff-encoding-bug

For what it's worth, this issue does *not* affect Molecule v1.15, but *does* affect 1.16 and 1.17. Setting `diff: no` in `molecule.yml` is a fine workaround for the nonce.

**Comment by retr0h** [comment]
Hey @conorsch - long time no hear from you!

Is this a dupe of #702?

**Comment by conorsch** [comment]
@retr0h Molecule's been working so well I haven't been hanging round these parts much!

Yes, I do believe we have a dupe here. Interesting that the author of #702 thinks it's related to _large_ diff output, I suspect that's a red herring. Moving conversation over there!
