### ISSUE TITLE
Doesn't run - AttributeError: 'module' object has no attribute 'Client'

### ISSUE THREAD

**Issue by timja-kainos** [metacloud/molecule#741]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides

molecule --version
molecule, version 1.19.1

docker --version
Docker version 1.13.0, build 49bf474

OS
Centos 7
```

- Molecule installation method: One of source, pip
pip
- Ansible installation method: One of source, pip, OS package
pip

# Desired Behaviour

Molecule should run

# Actual Behaviour (Bug report only)
Example repo:
https://github.com/timja-kainos/ansible-fpm/tree/add-molecule

Only command run on the repo is:
```
molecule init --driver docker
```

Generated molecule file fails to run at all:
```
[vagrant@localhost postgresql-role]$ molecule test
Traceback (most recent call last):
  File "/usr/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/molecule/command/create.py", line 69, in create
    c = Create(ctx.obj.get('args'), command_args)
  File "/usr/lib/python2.7/site-packages/molecule/command/base.py", line 60, in __init__
    self.main()
  File "/usr/lib/python2.7/site-packages/molecule/command/base.py", line 77, in main
    self.molecule.main()
  File "/usr/lib/python2.7/site-packages/molecule/core.py", line 56, in main
    self.driver = self._get_driver()
  File "/usr/lib/python2.7/site-packages/molecule/core.py", line 296, in _get_driver
    return dockerdriver.DockerDriver(self)
  File "/usr/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 38, in __init__
    self._docker = docker.Client(
AttributeError: 'module' object has no attribute 'Client'
```

(It works fine on my mac but trying to get it setup in CI and having issues.)

**Comment by dhutty** [comment]
Are you using the same version of docker-py on each platform?

**Comment by timja-kainos** [comment]
I didn't have `docker-py` installed on the centos box.

I had `docker` installed.

Which is incompatible.
see https://github.com/docker/docker-py/issues/1431

Installing `docker-py` seems to have fixed it for me
but compatibility with the `docker` pip package

**Comment by retr0h** [comment]
@timja-kainos reading the [quickstart](http://molecule.readthedocs.io/en/stable-1.19/#quick-start) would have saved you some time 😉
