### ISSUE TITLE
Cannot run brand new molecule role

### ISSUE THREAD

**Issue by sean-abbott** [metacloud/molecule#746]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.2.1.0
  config file = /home/sean/.ansible.cfg
  configured module search path = Default w/o overrides


molecule --version
molecule, version 1.20.0
```

- Molecule installation method:  pipsi
- Ansible installation method: pipsi

# Desired Behaviour

Be able to run molecule

# Actual Behaviour (Bug report only)
```
molecule --debug test
--> Destroying instances...
--> Checking playbook's syntax...
DEBUG: COMMAND
/home/sean/.local/bin/ansible-playbook playbook.yml --inventory-file=localhost, --syntax-check --limit=all --timeout=30 --become --diff

playbook: playbook.yml
--> Creating instances...
Traceback (most recent call last):
  File "/home/sean/.local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/home/sean/.local/venvs/molecule/local/lib/python2.7/site-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/home/sean/.local/venvs/molecule/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/sean/.local/venvs/molecule/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/sean/.local/venvs/molecule/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/sean/.local/venvs/molecule/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/sean/.local/venvs/molecule/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/sean/.local/venvs/molecule/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/sean/.local/venvs/molecule/local/lib/python2.7/site-packages/molecule/command/test.py", line 96, in test
    util.sysexit(t.execute()[0])
  File "/home/sean/.local/venvs/molecule/local/lib/python2.7/site-packages/molecule/command/test.py", line 44, in execute
    status, output = c.execute(exit=False)
  File "/home/sean/.local/venvs/molecule/local/lib/python2.7/site-packages/molecule/command/create.py", line 42, in execute
    self.molecule.driver.up(no_provision=True)
  File "/home/sean/.local/venvs/molecule/local/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 115, in up
    self._build_ansible_compatible_image()
  File "/home/sean/.local/venvs/molecule/local/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 221, in _build_ansible_compatible_image
    for tag in image.get('RepoTags', [])
TypeError: 'NoneType' object is not iterable
```

I just did a molecule init, per the instructions for an existing role ( molecule init --driver docker)
Was a fairly new role, was looking to test the playbook.  So could just be that I didn't read enough about how to use molecule. (But feel like stack trace in that case is..not idea.)

```
# tree
.
├── defaults
│   └── main.yml
├── files
├── handlers
│   └── main.yml
├── meta
│   └── main.yml
├── molecule.yml
├── playbook.yml
├── README.md
├── tasks
│   └── main.yml
├── templates
│   └── web.conf.j2
├── tests
│   ├── inventory
│   ├── test_default.py
│   ├── test_default.pyc
│   ├── test.retry
│   ├── test_role_requirements.yml
│   └── test.yml
└── vars
    └── main.yml
```

**Comment by abtreece** [comment]
@sean-abbott what does your molecule.yml contain?

**Comment by retr0h** [comment]
Seen this before with: https://github.com/metacloud/molecule/issues/548 and https://github.com/metacloud/molecule/issues/489.  It's not a Molecule issue, rather an issue with the images you have in your docker registry.

**Comment by abtreece** [comment]
Looks like they found a bug in the v2 docker-py... https://github.com/docker/docker-py/issues/1351
It's probably basically the same issue in the v1 code. I may try to pull an image w/out tags and see if I can reproduce.

**Comment by sean-abbott** [comment]
```yaml
---
dependency:
  name: galaxy
driver:
  name: docker
docker:
  containers:
    - name: www_capr
      image: ubuntu
      image_version: latest
      ansible_groups:
        - group1
verifier:
  name: testinfra
```

**Comment by sean-abbott** [comment]
So this appear to be fixed in the `docker` library, but (i.e. https://pypi.python.org/pypi/docker/) but perhaps not in the docker-py library (https://pypi.python.org/pypi/docker-py/1.10.6)

Both libraries share the same github page, so I assume the former is the current.

This fix is in the docker 2.0.x branch, but not in docker 1.10.x...is there a plan to migrate forward?  (not that there has to be a plan...just checking.

I haven't looked too deeply, but could we just wrap a try/except around this and ignore untagged images?

**Comment by abtreece** [comment]
@sean-abbott The version 2.0 Molecule will be migrating over to use Ansible as the middle man for Docker rather than interfacing with the Docker API directly. Version 1 of Molecule will not see an upgrade of the docker version being used.

The fastest way to get this fixed for Molecule v1 would be to figure out why it's still broke in the v1 docker-py and try to get them to fix it... who knows if they will do that having moved on to the newer version.

**Comment by sean-abbott** [comment]
Ok.  I already left them a comment to that effect, and I'll keep chasing them.  Thanks!

**Comment by retr0h** [comment]
Thanks @sean-abbott.  Thanks again @abtreece!

**Comment by lnunno** [comment]
I was seeing this when docker-py was grabbing untagged images and using those.
