### ISSUE TITLE
Fails if any images are untagged

### ISSUE THREAD

**Issue by timja-kainos** [metacloud/molecule#774]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
2.2.1.0
molecule --version
1.21.0
```

- Molecule installation method: One of pip
- Ansible installation method: One of pip

# Desired Behaviour

Not getting an error when an image is untagged

# Actual Behaviour (Bug report only)

molecule fails with a stacktrace if any image is untagged
```
Traceback (most recent call last):
  File "/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/molecule/command/create.py", line 71, in create
    util.sysexit(c.execute()[0])
  File "/usr/lib/python2.7/site-packages/molecule/command/create.py", line 42, in execute
    self.molecule.driver.up(no_provision=True)
  File "/usr/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 116, in up
    self._build_ansible_compatible_image()
  File "/usr/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 222, in _build_ansible_compatible_image
    for tag in image.get('RepoTags', [])
TypeError: 'NoneType' object is not iterable
```

Checking my docker images for untagged images shows:
```
$ docker images | grep "<none>"
nginx                                                                                 <none>              ba6bed934df2        5 months ago        181 MB
```
This happened because the nginx:latest tag was overridden when an update was pushed.

To get an image in this state:
1. Push an image to a registry tagged with latest
2. make a change to the image and push it tagged with latest
3. Pull the changed image to your machine
4. Run any molecule test

To remove the dangling image you can run:
`docker image prune`
but since we're running in a CI environment it would be great if molecule could handle this

The code its breaking on is 
```
        available_images = [
            tag.encode('utf-8')
            for image in self._docker.images()
            for tag in image.get('RepoTags', [])
        ]
```
I don't quite understand the syntax or I would try and fix it =/

This is related
https://github.com/docker/docker/issues/13215

**Comment by retr0h** [comment]
@timja-kainos I cannot reproduce this issue.  As you see I have images tagged with <none>.

```
[jodewey:~/git/molecule/test/scenarios/group_host_vars] [venv] master(+3/-0)+ ± docker images
REPOSITORY                                      TAG                 IMAGE ID            CREATED             SIZE
molecule_local/alpine                           latest              672503deb448        2 days ago          44.2 MB
molecule_local/centos                           7                   4ad11be6ef06        6 days ago          315 MB
molecule_local/ubuntu                           latest              e5ab6aa1534c        13 days ago         204 MB
containers.cisco.com/jodewey/kolla-kubernetes   latest              898f1be899f1        2 weeks ago         741 MB
testing                                         new                 ccc29c20ce45        2 weeks ago         614 MB
<none>                                          <none>              1413b3f950b5        2 weeks ago         590 MB
<none>                                          <none>              256c2825e491        2 weeks ago         590 MB
<none>                                          <none>              16f999af0b2a        2 weeks ago         590 MB
<none>                                          <none>              12f424cbde4e        2 weeks ago         590 MB
<none>                                          <none>              efa8a4c235c5        2 weeks ago         590 MB
<none>                                          <none>              15af29e6a039        2 weeks ago         590 MB
<none>                                          <none>              46614200ea84        2 weeks ago         590 MB
<none>                                          <none>              89d9e0f4c9db        2 weeks ago         590 MB
<none>                                          <none>              4db3ae039c88        2 weeks ago         468 MB
<none>                                          <none>              df3f666a05a8        2 weeks ago         452 MB
ubuntu                                          latest              0ef2e08ed3fa        2 weeks ago         130 MB
quay.io/coreos/etcd                             latest              d611dede458a        7 weeks ago         33.6 MB
quay.io/coreos/etcd                             v3.1.0              d611dede458a        7 weeks ago         33.6 MB
alpine                                          latest              88e169ea8f46        2 months ago        3.98 MB
centos                                          7                   67591570dd29        3 months ago        192 MB
centos                                          latest              67591570dd29        3 months ago        192 MB
```

```
$ ± molecule --version
molecule, version 1.21.0
$ ± pip freeze | grep docker
docker==2.1.0
docker-pycreds==0.2.1
```

**Comment by manics** [comment]
I'm also seeing this error after pulling an updated image. It's not enough just to have untagged images, and it also doesn't occur on all images.
```
$ python --version
Python 2.7.10

$ molecule --version
molecule, version 1.21.0

$ pip freeze | grep docker
docker==2.1.0
docker-pycreds==0.2.1

$ ansible --version
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides

$ docker version
Client:
 Version:      17.03.0-ce
 API version:  1.26
 Go version:   go1.7.5
 Git commit:   60ccb22
 Built:        Thu Feb 23 10:40:59 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      17.03.0-ce
 API version:  1.26 (minimum version 1.12)
 Go version:   go1.7.5
 Git commit:   3a232c8
 Built:        Tue Feb 28 07:52:04 2017
 OS/Arch:      linux/amd64
 Experimental: true
```
```
$ docker images
REPOSITORY                                       TAG                 IMAGE ID            CREATED             SIZE
molecule_local/centos                            7                   f663ea032fa5        7 minutes ago       315 MB
openmicroscopy/omero-grid                        latest              63d619a33cc0        18 hours ago        1.14 GB
openmicroscopy/omero-grid-web                    latest              5848250634b8        19 hours ago        1.01 GB
centos                                           latest              98d35105a391        19 hours ago        193 MB
molecule_local/centos/systemd                    latest              0fd15843465b        7 days ago          315 MB
test                                             latest              d5d51a44bf66        8 days ago          606 MB
molecule_local/manics/centos-systemd-ip-docker   latest              f76b1da25974        3 weeks ago         295 MB
manics/centos-systemd-ip-docker                  latest              1708fa87e527        4 weeks ago         214 MB
centos/systemd                                   latest              dc871c4e7c33        4 weeks ago         192 MB
openmicroscopy/omero-grid-web                    <none>              455d04d41fb3        2 months ago        988 MB
busybox                                          latest              7968321274dc        2 months ago        1.11 MB
centos                                           7                   67591570dd29        3 months ago        192 MB
manics/omerodev-docker                           latest              c0e644a6292e        7 months ago        1.53 GB
jupyterhub/jupyterhub                            0.6.1
```
```python
import docker
import pprint
c = docker.APIClient()
pprint.pprint([i for i in c.images() if i['RepoTags'] is None])
```
```
[{u'Containers': -1,
  u'Created': 1484431681,
  u'Id': u'sha256:455d04d41fb3b61e1eb781270de75ea7ff4910e5fb9a2b0f5e80ced9bd0f500f',
  u'Labels': {u'build-date': u'20161214',
              u'license': u'GPLv2',
              u'name': u'CentOS Base Image',
              u'vendor': u'CentOS'},
  u'ParentId': u'',
  u'RepoDigests': [u'openmicroscopy/omero-grid-web@sha256:9e4d7688ec6aaf80a8fe220caa627761d27188ec4a14932042c9bb08000017a0'],
  u'RepoTags': None,
  u'SharedSize': -1,
  u'Size': 987603224,
  u'VirtualSize': 987603224}]
```

**Comment by manics** [comment]
In my case `docker rmi 455d04d41fb3` allows molecule to work, and pulling it back results in the error again:
```
$ docker pull openmicroscopy/omero-grid-web@sha256:9e4d7688ec6aaf80a8fe220caa627761d27188ec4a14932042c9bb08000017a0

$ molecule test
...
  File "/Users/spli/venvs/default/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 116, in up
    self._build_ansible_compatible_image()
  File "/Users/spli/venvs/default/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 222, in _build_ansible_compatible_image
    for tag in image.get('RepoTags', [])
TypeError: 'NoneType' object is not iterable
```

**Comment by retr0h** [comment]
@manics I can't reproduce.

```
[jodewey:~/git/molecule/test/scenarios/group_host_vars] [venv] master(+3/-0)+ ± docker pull openmicroscopy/omero-grid-web@sha256:9e4d7688ec6aaf80a8fe2[42/210]
761d27188ec4a14932042c9bb08000017a0
```

```
[jodewey:~/git/molecule/test/scenarios/group_host_vars] [venv] master(+3/-0)+ 1 ± docker images | grep openmicroscopy
openmicroscopy/omero-grid-web                   <none>              455d04d41fb3        2 months ago        988 MB
```

```
[jodewey:~/git/molecule/test/scenarios/group_host_vars] [venv] master(+3/-0)+ ± molecule converge
--> Starting Ansible Run...

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [group-vars-scenario]

TASK [Group host vars scenario test group vars] ********************************
ok: [group-vars-scenario]

TASK [Group host vars scenario test example group vars from molecule.yml] ******
ok: [group-vars-scenario]

TASK [Group host vars scenario test example2:children group vars from molecule.yml] ***
ok: [group-vars-scenario]

TASK [Group host vars scenario test host vars] *********************************
ok: [group-vars-scenario]

TASK [Group host vars scenario test host vars from molecule.yml] ***************
ok: [group-vars-scenario]

PLAY RECAP *********************************************************************
group-vars-scenario        : ok=6    changed=0    unreachable=0    failed=0
```

**Comment by retr0h** [comment]
@manics Thanks
