### ISSUE TITLE
Host/Group Vars do not seem to work

### ISSUE THREAD

**Issue by lxhunter** [metacloud/molecule#775]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version 
$> 2.2.1.0
molecule --version
$> 1.17.3
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

Load group/vars as defined [here](https://molecule.readthedocs.io/en/stable-1.21/configuration.html#host-group-vars)

```yaml
ansible:
  playbook: playbook.yml
  group_vars:
    foo1:
      foo: bar
      baz:
        key: value
    foo2:
      foo: bar
  host_vars:
    foo1-01:
      set_this_value: True
```

# Actual Behaviour (Bug report only)

```python
Traceback (most recent call last):
  File "/Users/a.jaeger/.virtualenvs/xsite/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/Users/a.jaeger/.virtualenvs/xsite/lib/python2.7/site-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/Users/a.jaeger/.virtualenvs/xsite/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Users/a.jaeger/.virtualenvs/xsite/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Users/a.jaeger/.virtualenvs/xsite/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/a.jaeger/.virtualenvs/xsite/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/a.jaeger/.virtualenvs/xsite/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Users/a.jaeger/.virtualenvs/xsite/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/a.jaeger/.virtualenvs/xsite/lib/python2.7/site-packages/molecule/command/converge.py", line 130, in converge
    c = Converge(ctx.obj.get('args'), command_args)
  File "/Users/a.jaeger/.virtualenvs/xsite/lib/python2.7/site-packages/molecule/command/base.py", line 60, in __init__
    self.main()
  File "/Users/a.jaeger/.virtualenvs/xsite/lib/python2.7/site-packages/molecule/command/base.py", line 77, in main
    self.molecule.main()
  File "/Users/a.jaeger/.virtualenvs/xsite/lib/python2.7/site-packages/molecule/core.py", line 80, in main
    self._add_or_update_vars('group_vars')
  File "/Users/a.jaeger/.virtualenvs/xsite/lib/python2.7/site-packages/molecule/core.py", line 327, in _add_or_update_vars
    target_var_content = vars_target[target][0]
KeyError: 0
```

**Comment by lxhunter** [comment]
Seem to work now... sorry
