### ISSUE TITLE
Problems with molecule verify(using molecule 1.2.0)

### ISSUE THREAD

**Issue by oserde** [metacloud/molecule#79]
Hi,

I have problems with molecule verify. When I execute molecule test, I get the following output:

    Traceback (most recent call last):
    File "/home/oscar/project/.venv/bin/molecule", line 11, in <module>
    sys.exit(main())
    File "/home/oscar/project/.venv/local/lib/python2.7/site-packages/molecule/cli.py", line 87, in main
    CLI().main()
    File "/home/oscar/project/.venv/local/lib/python2.7/site-packages/molecule/cli.py", line 83, in main
    sys.exit(method())
    File "/home/oscar/project/.venv/local/lib/python2.7/site-packages/molecule/commands.py", line 76, in test
    self.commands.test()
    File "/home/oscar/project/.venv/local/lib/python2.7/site-packages/molecule/commands.py", line 284, in test
    m()
    File "/home/oscar/project/.venv/local/lib/python2.7/site-packages/molecule/commands.py", line 243, in verify
    self.molecule._write_ssh_config()
    File "/home/oscar/project/.venv/local/lib/python2.7/site-packages/molecule/core.py", line 138, in _write_ssh_config
    out = self._vagrant.ssh_config()
    File "/home/oscar/project/.venv/local/lib/python2.7/site-packages/vagrant/__init__.py", line 545, in ssh_config
    return self._run_vagrant_command(['ssh-config', vm_name])
    File "/home/oscar/project/.venv/local/lib/python2.7/site-packages/vagrant/__init__.py", line 883, in _run_vagrant_command
    env=self.env, stderr=err_fh))
    File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
    File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
    File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
    TypeError: execve() arg 3 contains a non-string value

While molecule test returns  that error(note it crashes in the verify part), if I execute all stages separately(molecule create, molecule converge,etc.) everything works properly. I have been checking environment variables, and , even though there are some differences(between executing molecule test and molecule verify separately), I have not been able to find what is causing the problem.

Nevertheless, with other versions of molecule (such as version 1.0.5) I have no issues at all.

**Comment by abrown-sg** [comment]
@oserde I just released 1.2.1 a few minutes ago with an edge case fix for the idempotence test. Does it exhibit the same behavior?

**Comment by abrown-sg** [comment]
@oserde Out of curiosity, what version of python-vagrant are you using?

**Comment by oserde** [comment]
Well. Now it works fine. Thank you.

I am using 0.5.9 and 0.5.10(for some tests I perform in a virtualenv)
