### ISSUE TITLE
Idempotence check throws exception when a non-idempotent task is found and user does not set ANSIBLE_NOCOWS=1

### ISSUE THREAD

**Issue by ehashman** [metacloud/molecule#800]
# Issue Type

- Bug report

# Molecule and Ansible details

```
$ ansible --version
ansible 2.2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/usr/share/ansible']

$ molecule --version
molecule, version 1.23.0
```

- Molecule installation method: pip (in virtualenv)
- Ansible installation method: pip (in virtualenv)

# Desired Behaviour

When I run an idempotence check that fails, I expect it to print an error listing the tasks that failed at idempotence.

# Actual Behaviour

I get a stacktrace indicating a regex match failed.

<details>
<h2>Stacktrace:</h2>
<pre>
ERROR: Idempotence test failed because of the following tasks:
Traceback (most recent call last):
  File "/home/elana/src/rms-di-infrastructure/ansible/.ansible-venv/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/home/elana/src/rms-di-infrastructure/ansible/.ansible-venv/local/lib/python2.7/site-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/home/elana/src/rms-di-infrastructure/ansible/.ansible-venv/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/elana/src/rms-di-infrastructure/ansible/.ansible-venv/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/elana/src/rms-di-infrastructure/ansible/.ansible-venv/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/elana/src/rms-di-infrastructure/ansible/.ansible-venv/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/elana/src/rms-di-infrastructure/ansible/.ansible-venv/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/elana/src/rms-di-infrastructure/ansible/.ansible-venv/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/elana/src/rms-di-infrastructure/ansible/.ansible-venv/local/lib/python2.7/site-packages/molecule/command/idempotence.py", line 120, in idempotence
    util.sysexit(i.execute()[0])
  File "/home/elana/src/rms-di-infrastructure/ansible/.ansible-venv/local/lib/python2.7/site-packages/molecule/command/idempotence.py", line 59, in execute
    util.print_error('\n'.join(self._non_idempotent_tasks(output)))
  File "/home/elana/src/rms-di-infrastructure/ansible/.ansible-venv/local/lib/python2.7/site-packages/molecule/command/idempotence.py", line 104, in _non_idempotent_tasks
    task_name = re.search(r'\[(.*)\]', task_line).groups()[0]
AttributeError: 'NoneType' object has no attribute 'groups'
</pre>
</details>

# Suggested solution

Ensure that the environment variable (or general configuration) `ANSIBLE_NOCOWS=1` is set for all molecule runs.

# More details

The issue clearly affects the [_non_idempotent_tasks](https://github.com/metacloud/molecule/blob/e668f46ccc4cf0843bf4e8e5126244f46dd257f3/molecule/command/idempotence.py#L85) method in `molecule/command/idempotence.py`.

Here is a relevant snippet of what's bound to `output_lines` when we don't set `ANSIBLE_NOCOWS`:

```
< TASK [role : Some task name] >
---------------------------------------------------
\   ^__^
\  (oo)\_______
(__)\       )\/\
||----w |
||     ||
changed: [hostname]
```

Here is what `output_lines` looks like when we do set it:

```
TASK [role : Some task name] ******************************
changed: [hostname]
```

The issue stems from the following code: https://github.com/metacloud/molecule/blob/e668f46ccc4cf0843bf4e8e5126244f46dd257f3/molecule/command/idempotence.py#L96-L105

Since the cowsay version line with the taskname does not start with TASK and does not conform to the expected regexes in lines 103/104, the code blows up with a stacktrace when the regex match fails.

**Comment by retr0h** [comment]
Thanks for the report @ehashman
