### ISSUE TITLE
"Rpmdb checksum is invalid" problem occurs in CoreOS

### ISSUE THREAD

**Issue by yife** [metacloud/molecule#813]
# Issue Type
- Bug report

Installing `sudo` package with yum package manager on CoreOS will fail with checksum error.
It seems a docker's bug (cf. [docker issue](https://github.com/docker/docker/issues/10180) and [Oracle's page](https://docs.oracle.com/cd/E52668_01/E69348/html/uek4-czc_xmc_xt.html)).
We have to work around that with `touch /var/lib/rpm/*` before ` yum install -y python sudo yum-plugin-ovl bash`.

# Molecule and Ansible details

```
root@e51b1ed90ce3:~# ansible --version
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr 25 2017, 04:23:34) [GCC 4.9.2]
root@e51b1ed90ce3:~# molecule --version
molecule, version 1.24.0
```
- https://hub.docker.com/r/yife/docker_molecule/
  - Molecule installation method:  pip
  - Ansible installation method:  pip

# Desired Behaviour

Successfully done a build of ansible compatible image locally.

```
root@e51b1ed90ce3:~/sl6_ansible_roles/ansible# molecule test
--> Destroying instances...
--> Checking playbook's syntax...

playbook: playbook.yml
--> Creating instances...
--> Creating Ansible compatible image of yife/slc6_coreos:latest ...
--> Building ansible compatible image...
...(abbr)
Finished building molecule_local/yife/slc6_coreos:latest.
```

# Actual Behaviour (Bug report only)

```
--> Building ansible compatible image...
	Step 1/8 : FROM yife/slc6_coreos:latest
	 ---> d274df7629cf
	Step 2/8 : RUN /bin/sh -c 'if [ -x "$(command -v apt-get)" ]; then apt-get update && apt-get install -y python sudo bash; fi'
	 ---> Running in 8f855195f1a5
	 ---> d902656da987
	Step 3/8 : RUN /bin/sh -c 'if [ -x "$(command -v yum)" ]; then yum makecache fast && yum update -y && yum install -y python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf; fi'
	 ---> Running in 83482e4ecdb4
	Loaded plugins: changelog, kernel-module, protectbase, tsflags, versionlock


	Metadata Cache Created
	Loaded plugins: changelog, kernel-module, protectbase, tsflags, versionlock
	Setting up Update Process
	156 packages excluded due to repository protections
	No Packages marked for Update
	Loaded plugins: changelog, kernel-module, protectbase, tsflags, versionlock
	Setting up Install Process
	156 packages excluded due to repository protections
	Package python-2.6.6-66.el6_8.x86_64 already installed and latest version
	Package bash-4.1.2-48.el6.x86_64 already installed and latest version
	Resolving Dependencies
	--> Running transaction check
	---> Package sudo.x86_64 0:1.8.6p3-27.el6 will be installed
	---> Package yum-plugin-ovl.noarch 0:1.1.30-40.el6 will be installed
	--> Finished Dependency Resolution
	Beginning Kernel Module Plugin
	Finished Kernel Module Plugin

Dependencies Resolved

================================================================================
 Package               Arch          Version               Repository      Size
================================================================================
Installing:
 sudo                  x86_64        1.8.6p3-27.el6        slc6-os        710 k
 yum-plugin-ovl        noarch        1.1.30-40.el6         slc6-os         25 k

Transaction Summary
================================================================================
Install       2 Package(s)
	Total download size: 735 k
Installed size: 2.4 M
Downloading Packages:
	--------------------------------------------------------------------------------
	Total                                           212 kB/s | 735 kB     00:03
	Running rpm_check_debug
	Running Transaction Test
	Transaction Test Succeeded
	Running Transaction
  Installing : sudo-1.8.6p3-27.el6.x86_64                                   1/2

  Installing : yum-plugin-ovl-1.1.30-40.el6.noarch                          2/2


Rpmdb checksum is invalid: dCDPT(pkg checksums): sudo.x86_64 0:1.8.6p3-27.el6 - u


	The command '/bin/sh -c /bin/sh -c 'if [ -x "$(command -v yum)" ]; then yum makecache fast && yum update -y && yum install -y python sudo yum-plugin-ovl bash && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf; fi'' returned a non-zero code: 1
ERROR: Build failed for molecule_local/yife/slc6_coreos:latest.
Creating container ansible with base image yife/slc6_coreos:latest...
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/molecule/command/test.py", line 96, in test
    util.sysexit(t.execute()[0])
  File "/usr/local/lib/python2.7/site-packages/molecule/command/test.py", line 44, in execute
    status, output = c.execute(exit=False)
  File "/usr/local/lib/python2.7/site-packages/molecule/command/create.py", line 42, in execute
    self.molecule.driver.up(no_provision=True)
  File "/usr/local/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 172, in up
    hostname=hostname)
  File "/usr/local/lib/python2.7/site-packages/docker/api/container.py", line 446, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python2.7/site-packages/docker/api/container.py", line 457, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python2.7/site-packages/docker/api/client.py", line 220, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python2.7/site-packages/docker/api/client.py", line 216, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/site-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: molecule_local/yife/slc6_coreos:latest")
```

**Comment by yife** [comment]
Problem fixed.
