### ISSUE TITLE
Unable to run tests when using environment

### ISSUE THREAD

**Issue by Moep90** [metacloud/molecule#824]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.3.0.0
  config file = /Users/username/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jan  9 2017, 09:22:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```
```
molecule --version
molecule, version 1.24.0
```

- Molecule installation method: pip
- Ansible installation method: brew

# Desired Behaviour

Create Containers with different flavors 

# Actual Behaviour (Bug report only)
```
---
ansible:
  playbook: ci_playbook.yml
dependency:
  name: galaxy
driver:
  name: docker
docker:
  containers:
    - name: ubuntu14.04
      image: ubuntu
      image_version: "14.04"
      environment: container=docker"
      cap_add:
        - SYS_ADMIN
      command: "/usr/sbin/init"
      volume_mounts:
        - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      ansible_groups:
        - group1
    - name: centos7
      image: centos
      image_version: "7"
      environment: container=docker"
      cap_add:
        - SYS_ADMIN
      command: "/usr/sbin/init"
      volume_mounts:
        - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      ansible_groups:
        - group1
    - name: debian8
      image: debian
      image_version: "8"
      environment: container=docker
      cap_add:
        - SYS_ADMIN
      command: "/usr/sbin/init"
      volume_mounts:
        - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      ansible_groups:
        - group1
#verifier:
#  name: testinfra
```
```
molecule --debug test
--> Destroying instances...
--> Checking playbook's syntax...
DEBUG: COMMAND
/usr/local/bin/ansible-playbook ci_playbook.yml --inventory-file=localhost, --syntax-check --limit=all --timeout=30 --become --diff

playbook: ci_playbook.yml
--> Creating instances...
--> Creating Ansible compatible image of ubuntu:14.04 ...
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/molecule/command/test.py", line 96, in test
    util.sysexit(t.execute()[0])
  File "/usr/local/lib/python2.7/site-packages/molecule/command/test.py", line 44, in execute
    status, output = c.execute(exit=False)
  File "/usr/local/lib/python2.7/site-packages/molecule/command/create.py", line 42, in execute
    self.molecule.driver.up(no_provision=True)
  File "/usr/local/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 133, in up
    self._build_ansible_compatible_image(container)
  File "/usr/local/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 289, in _build_ansible_compatible_image
    for k, v in environment.iteritems())
AttributeError: 'str' object has no attribute 'iteritems'
```

**Comment by retr0h** [comment]
Looks like environment should be a [dict](https://github.com/metacloud/molecule/blob/962a94476ae3a53fa8cc8fb37faa0d7fd249a90a/test/unit/conftest.py#L280-L282) not a string as you provided in molecule.yml.

Instead try:

```
  containers:
    - name: ubuntu14.04
      image: ubuntu
      image_version: "14.04"
      environment:
        container: docker
      cap_add:
        - SYS_ADMIN
      command: "/usr/sbin/init"
      volume_mounts:
        - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      ansible_groups:
        - group1
```

**Comment by Moep90** [comment]
unfortunatly is it also not working...

´´´
---
ansible:
  playbook: ci_playbook.yml
dependency:
  name: galaxy
driver:
  name: docker
docker:
  containers:
    - name: ubuntu14.04
      image: ubuntu
      image_version: "14.04"
      environment:
        container: docker
      cap_add:
        - SYS_ADMIN
      command: "/usr/sbin/init"
      volume_mounts:
        - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      ansible_groups:
        - group1
    - name: centos7
      image: centos
      image_version: "7"
      environment:
        container: docker
      cap_add:
        - SYS_ADMIN
      command: "/usr/sbin/init"
      volume_mounts:
        - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      ansible_groups:
        - group1
    - name: debian8
      image: debian
      image_version: "8"
      environment:
        container: docker
      cap_add:
        - SYS_ADMIN
      command: "/usr/sbin/init"
      volume_mounts:
        - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      ansible_groups:
        - group1
#verifier:
#  name: testinfra
´´´

```
molecule test
--> Destroying instances...
--> Checking playbook's syntax...

playbook: ci_playbook.yml
--> Creating instances...
--> Creating Ansible compatible image of ubuntu:14.04 ...
Creating container ubuntu14.04 with base image ubuntu:14.04...
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/molecule/command/test.py", line 96, in test
    util.sysexit(t.execute()[0])
  File "/usr/local/lib/python2.7/site-packages/molecule/command/test.py", line 44, in execute
    status, output = c.execute(exit=False)
  File "/usr/local/lib/python2.7/site-packages/molecule/command/create.py", line 42, in execute
    self.molecule.driver.up(no_provision=True)
  File "/usr/local/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 173, in up
    self._docker.start(container=container.get('Id'))
  File "/usr/local/lib/python2.7/site-packages/docker/utils/decorators.py", line 21, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/docker/api/container.py", line 1068, in start
    self._raise_for_status(res)
  File "/usr/local/lib/python2.7/site-packages/docker/api/client.py", line 216, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python2.7/site-packages/docker/errors.py", line 30, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error: Not Found ("oci runtime error: container_linux.go:247: starting container process caused "exec: \"/usr/sbin/init\": stat /usr/sbin/init: no such file or directory"
")
```

**Comment by retr0h** [comment]
> docker.errors.NotFound: 404 Client Error: Not Found ("oci runtime error: container_linux.go:247: starting container process caused "exec: \"/usr/sbin/init\": stat /usr/sbin/init: no such file or directory"
> ")

That doesn't look like a problem with molecule but rather a problem with your setup.  It is telling you `/usr/sbin/init` does not exist 🥇 

```
[jodewey:~/git/molecule/test/scenarios/command_test] [molecule-env-2.7.13] master(+76/-30) ± docker run -it molecule_local/ubuntu bash
root@d1a7605c1107:/# ls -l /usr/sbin/init
ls: cannot access '/usr/sbin/init': No such file or directory
```

I think you mean

```
  containers:
    - name: ubuntu14.04
      image: ubuntu
      image_version: "14.04"
      environment:
        container: docker
      cap_add:
        - SYS_ADMIN
      command: "/sbin/init"
      volume_mounts:
        - "/sys/fs/cgroup:/sys/fs/cgroup:ro"
      ansible_groups:
        - group1
```

**Comment by Moep90** [comment]
All right, so Is there any Suite where I can run my playbooks also against systemd services while using docker as a provisioner? Because that is what I had hoped for when starting to use molecule...
Right now, I think Ive just the possibility to use vagrant for fat VM provisioning...

**Comment by retr0h** [comment]
Yes, you [can](https://github.com/retr0h/ansible-etcd/blob/master/molecule.yml).
