### ISSUE TITLE
Docker driver broken looking for docker.APIClient

### ISSUE THREAD

**Issue by miticojo** [metacloud/molecule#825]
# Issue Type
- Bug report

# Molecule and Ansible details
ansible 2.3.0.0
molecule, version 1.24.0
Docker version 1.12.6

- Molecule installation method: pip
- Ansible installation method: OS package
- Docker installation method: OS package (Fedora 25)

# Desired Behaviour
Run role test with docker driver 

# Actual Behaviour (Bug report only)
Running role with docker driver got following error
```
Traceback (most recent call last):
  File "/usr/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/molecule/command/test.py", line 94, in test
    t = Test(ctx.obj.get('args'), command_args)
  File "/usr/lib/python2.7/site-packages/molecule/command/base.py", line 60, in __init__
    self.main()
  File "/usr/lib/python2.7/site-packages/molecule/command/base.py", line 83, in main
    self.molecule.main()
  File "/usr/lib/python2.7/site-packages/molecule/core.py", line 57, in main
    self.driver = self._get_driver()
  File "/usr/lib/python2.7/site-packages/molecule/core.py", line 312, in _get_driver
    return dockerdriver.DockerDriver(self)
  File "/usr/lib/python2.7/site-packages/molecule/driver/dockerdriver.py", line 39, in __init__
    self._docker = docker.APIClient(
AttributeError: 'module' object has no attribute 'APIClient'
```

**Comment by retr0h** [comment]
See #782 and #771.
