### ISSUE TITLE
Unable to load extension: cannot import name _thread when creating a role

### ISSUE THREAD

**Issue by dj-wasabi** [metacloud/molecule#828]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version:
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 14 2015, 19:46:27) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]
molecule --version: molecule, version 1.24.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

When creating a role with: 
```
molecule init --driver docker --role ansible-meetup
```
I would like to have a role created, with the basic directory structure and molecule configuration

# Actual Behaviour (Bug report only)

I'm trying to create a role with the molecule init command with the docker driver. But when executing the command, i get the following message:

```
molecule init --driver docker --role ansible-meetup
--> Initializing role ansible-meetup...
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/Library/Python/2.7/site-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/2.7/site-packages/molecule/command/init.py", line 141, in init
    util.sysexit(i.execute()[0])
  File "/Library/Python/2.7/site-packages/molecule/command/init.py", line 60, in execute
    self._init_new_role(role, role_path, driver, verifier)
  File "/Library/Python/2.7/site-packages/molecule/command/init.py", line 85, in _init_new_role
    util.process_templates(template, extra_context, role_path)
  File "/Library/Python/2.7/site-packages/molecule/util.py", line 115, in process_templates
    no_input=True, )
  File "/Library/Python/2.7/site-packages/cookiecutter/main.py", line 82, in cookiecutter
    context['cookiecutter'] = prompt_for_config(context, no_input)
  File "/Library/Python/2.7/site-packages/cookiecutter/prompt.py", line 188, in prompt_for_config
    env = StrictEnvironment(context=context)
  File "/Library/Python/2.7/site-packages/cookiecutter/environment.py", line 70, in __init__
    **kwargs
  File "/Library/Python/2.7/site-packages/cookiecutter/environment.py", line 40, in __init__
    raise UnknownExtension('Unable to load extension: {}'.format(err))
cookiecutter.exceptions.UnknownExtension: Unable to load extension: cannot import name _thread
```
I did update molecule to latest version, but did not help. Running MacOSX 10.10 (Yeah I know, pretty old)

**Comment by retr0h** [comment]
@dj-wasabi odd, it works for me.... 

```
[jodewey:~/git/molecule] [molecule-env-2.7.13] master ± molecule init --driver docker --role ansible-meetup
--> Initializing role ansible-meetup...
Successfully initialized new role in /Users/jodewey/git/molecule/ansible-meetup.
```

What version of cookiecutter are you using?  Did you pip install -U all of your dependencies recently?

```
[jodewey:~/git/molecule] [molecule-env-2.7.13] master* 1 ± pip freeze | grep cookiecutter
cookiecutter==1.5.1
```

**Comment by dj-wasabi** [comment]
Sorry, probably bad installation. I did a virtualenv and installed everything and works like a charm. You may close this, on my other laptop it is working too.

P.S. Had no issues. :-) Was preparing for an Ansible Meetup here and will talk about Testing roles with Molecule .. :-)

**Comment by retr0h** [comment]
@dj-wasabi awesome!  Share your preso sometime if you can!
