### ISSUE TITLE
openstack driver trying to assign a floating ip, even when ip_pool set to None explicitly in molecule.yml

### ISSUE THREAD

**Issue by VuokkoVuorinnen** [metacloud/molecule#866]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version: ansible 2.3.0.0
molecule --version: molecule, version 1.24.0
```

- Molecule installation method: pip
- Ansible installation method: OS package

# Desired Behaviour

molecule creating an instance in our openstack on the specified network, without trying to attach a floating ip

# Actual Behaviour (Bug report only)

molecule.yml:
```
---
driver:
  name: openstack
openstack:
  ssh_timeout: 300
  instances:
    - name: "molecule-test"
      image: 'CentOS-7-x86_64-GenericCloud-1608.qcow2'
      flavor: m1.small
      sshuser: centos
      networks: "${OS_NETWORK_ID}"
      ip_pool: None
verifier:
  name: goss
```

And yet molecule fails with the following output:

```
--> 	 Waiting for instance molecule-test to be in state active...
Traceback (most recent call last):
  File "/usr/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/molecule/cli.py", line 41, in main
    cli(obj={})
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/molecule/command/test.py", line 96, in test
    util.sysexit(t.execute()[0])
  File "/usr/lib/python2.7/site-packages/molecule/command/test.py", line 44, in execute
    status, output = c.execute(exit=False)
  File "/usr/lib/python2.7/site-packages/molecule/command/converge.py", line 67, in execute
    c.execute()
  File "/usr/lib/python2.7/site-packages/molecule/command/create.py", line 42, in execute
    self.molecule.driver.up(no_provision=True)
  File "/usr/lib/python2.7/site-packages/molecule/driver/openstackdriver.py", line 173, in up
    instance['server'], auto_ip=True)
  File "/usr/lib/python2.7/site-packages/shade/openstackcloud.py", line 5584, in wait_for_server
    nat_destination=nat_destination)
  File "/usr/lib/python2.7/site-packages/shade/openstackcloud.py", line 5608, in get_active_server
    wait=wait, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/shade/openstackcloud.py", line 5239, in add_ips_to_server
    server, wait=wait, timeout=timeout, reuse=reuse)
  File "/usr/lib/python2.7/site-packages/shade/openstackcloud.py", line 5200, in _add_auto_ip
    skip_attach=skip_attach)
  File "/usr/lib/python2.7/site-packages/shade/openstackcloud.py", line 4872, in _attach_ip_to_server
    wait=self._SERVER_AGE):
  File "/usr/lib/python2.7/site-packages/shade/_utils.py", line 77, in _iterate_timeout
    raise exc.OpenStackCloudTimeout(message)
shade.exc.OpenStackCloudTimeout: Timeout waiting for the floating IP to be attached. (Inner Exception: unable to bind a floating ip to server df769c32-04d8-4051-b3f6-0c16f2cbe720: External network eff3dd95-0aad-4848-a20e-607316b25f9b is not reachable from subnet cde2b082-d0e1-44d5-8ef0-dba1e43e80b6.  Therefore, cannot associate Port 6e1adf57-caf3-4c80-80d9-561d930ef2d1 with a Floating IP.
Neutron server returns request_ids: ['req-05a239a7-93ad-45fd-b9fc-33786a848af9'])
```

I have a shared external network setup, but I do not want to use it for molecule tests. It should only use the specified network and not assign a floating ip

**Comment by retr0h** [comment]
Doesn't look like anyone in the community is interested in fixing this for v1.

**Comment by retr0h** [comment]
@VuokkoVuorinnen I recommend moving to Molecule v2.  This isn't going to be fixed under v1.  Please let us know if you have any issues with v2.
