### ISSUE TITLE
Can't alter the test sequence in molecule 2.0.0.0rc14?

### ISSUE THREAD

**Issue by butla** [metacloud/molecule#914]
# Issue Type

- Bug report (?)

# Molecule and Ansible details

```
ansible 2.3.2.0
  config file = /home/butla/.ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

molecule, version 2.0.0.0rc14
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

I want to be able to alter the test sequence of a scenario. In the release candidate versions I was doing that by setting this in `molecule.yml` from my scenario:
```
scenario:
  name: default
  test_sequence:
    - lint
    - destroy
    - create
    - converge
    - destroy
```

I'm altering the test sequence to disable checking for idempotence (yes, I know that's bad, but that's the sad reality of my client's install scripts) and to put linting as the first step (because it gives way faster responses then actually running the Ansible roles).

What's the way to do that now?

# Actual Behaviour (Bug report only)

It was working in rc12, but stopped when I updated to rc14
The error I'm getting:
```
Traceback (most recent call last):
  File "/home/butla/.local/bin/molecule", line 11, in <module>
    sys.exit(main())
  File "/home/butla/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/butla/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/butla/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/butla/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/butla/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/butla/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/butla/.local/lib/python2.7/site-packages/molecule/command/test.py", line 93, in test
    base.get_configs(args, command_args), scenario_name)
  File "/home/butla/.local/lib/python2.7/site-packages/molecule/command/base.py", line 114, in get_configs
    command_args=command_args) for c in glob.glob(MOLECULE_GLOB)
  File "/home/butla/.local/lib/python2.7/site-packages/molecule/config.py", line 83, in __init__
    self.config = self._combine()
  File "/home/butla/.local/lib/python2.7/site-packages/molecule/config.py", line 240, in _combine
    schema.validate(base)
  File "/home/butla/.local/lib/python2.7/site-packages/molecule/model/schema.py", line 182, in validate
    return schema.load(c)
  File "/home/butla/.local/lib/python2.7/site-packages/marshmallow/schema.py", line 580, in load
    result, errors = self._do_load(data, many, partial=partial, postprocess=True)
  File "/home/butla/.local/lib/python2.7/site-packages/marshmallow/schema.py", line 701, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'scenario': {'test_sequence': ['Unknown field']}}
```

**Comment by retr0h** [comment]
Try this.

```
scenario:
  name: default
  test_sequences:
    - lint
    - destroy
    - create
    - converge
    - destroy
```

This was recently [changed](https://molecule.readthedocs.io/en/latest/configuration.html#scenario) in rc14.

**Comment by butla** [comment]
No problem - keep the progress going :) Thanks for the quick response.

BTW, why the plural form? Every item in the list is regarded as a sequence?

**Comment by retr0h** [comment]
> BTW, why the plural form? Every item in the list is regarded as a sequence?

It's prob bad naming on my part.  I probably should change it back.  I started heading down a direction that I probably shouldn't have.

**Comment by butla** [comment]
Hmm... maybe you could accept both names but raise a [deprecation warning](https://docs.python.org/2/library/exceptions.html#exceptions.DeprecationWarning) for the unwanted one? You could say to "change your code util such and such date" or your code stops working. But I don't know if that's possible with Marshmallow...

**Comment by retr0h** [comment]
I'm going to change it back since sequences really isn't the proper term.

Since I have been working on a non released version of Molecule, I have broken things more than I would have if this were released.  In the future we will not break the API like this.

**Comment by butla** [comment]
All right. Just give a warning when this changes again :)

I don't think I have any further feedback - everythings I'm using seems fine.
When do you plan to release the first official v2?

**Comment by retr0h** [comment]
Master has been changed back to `sequence`.
