### ISSUE TITLE
Openstack driver should have a way to consume credentials from clouds.yml as required for shade to work.

### ISSUE THREAD

**Issue by bhavikbhavsar** [metacloud/molecule#932]
# Issue Type
Openstack driver should have a way to consume credentials from clouds.yml as required for shade to work.
- Bug report
```
    TASK [Create security group] ***************************************************
    task path: /home/pnq/bbhavsar/src/molecule_test/mol/foo/molecule/default/security_groups.yml:2
    Using module file /home/pnq/bbhavsar/src/molecule_test/mol/lib/python2.7/site-packages/ansible/modules/cloud/openstack/os_security_group.py
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: bbhavsar
    <127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1504047619.24-101187221688261 `" && echo ansible-tmp-1504047619.24-101187221688261="` echo /root/.ansible/tmp/ansible-tmp-1504047619.24-101187221688261 `" ) && sleep 0'
    <127.0.0.1> PUT /tmp/tmpAv_wJ8 TO /root/.ansible/tmp/ansible-tmp-1504047619.24-101187221688261/os_security_group.py
    <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1504047619.24-101187221688261/ /root/.ansible/tmp/ansible-tmp-1504047619.24-101187221688261/os_security_group.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '/home/pnq/bbhavsar/src/molecule_test/mol/bin/python2 /root/.ansible/tmp/ansible-tmp-1504047619.24-101187221688261/os_security_group.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1504047619.24-101187221688261/" > /dev/null 2>&1 && sleep 0'
    The full traceback is:
    Traceback (most recent call last):
      File "/tmp/ansible_Cu0Lg8/ansible_module_os_security_group.py", line 152, in <module>
        main()
      File "/tmp/ansible_Cu0Lg8/ansible_module_os_security_group.py", line 119, in main
        cloud = shade.openstack_cloud(**module.params)
      File "/home/pnq/bbhavsar/src/molecule_test/mol/lib/python2.7/site-packages/shade/__init__.py", line 109, in openstack_cloud
        cloud_config = config.get_one_cloud(**kwargs)
      File "/home/pnq/bbhavsar/src/molecule_test/mol/lib/python2.7/site-packages/os_client_config/config.py", line 1074, in get_one_cloud
        auth_plugin = loader.load_from_options(**config['auth'])
      File "/home/pnq/bbhavsar/src/molecule_test/mol/lib/python2.7/site-packages/keystoneauth1/loading/base.py", line 162, in load_from_options
        raise exceptions.MissingRequiredOptions(missing_required)
    keystoneauth1.exceptions.auth_plugins.MissingRequiredOptions: Auth plugin requires parameters which were not given: auth_url
   
    fatal: [localhost]: FAILED! => {
        "changed": false,
        "failed": true,
        "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_Cu0Lg8/ansible_module_os_security_group.py\", line 152, in <module>\n    main()\n  File \"/tmp/ansible_Cu0Lg8/ansible_module_os_security_group.py\", line 119, in main\n    cloud = shade.openstack_cloud(**module.params)\n  File \"/home/pnq/bbhavsar/src/molecule_test/mol/lib/python2.7/site-packages/shade/__init__.py\", line 109, in openstack_cloud\n    cloud_config = config.get_one_cloud(**kwargs)\n  File \"/home/pnq/bbhavsar/src/molecule_test/mol/lib/python2.7/site-packages/os_client_config/config.py\", line 1074, in get_one_cloud\n    auth_plugin = loader.load_from_options(**config['auth'])\n  File \"/home/pnq/bbhavsar/src/molecule_test/mol/lib/python2.7/site-packages/keystoneauth1/loading/base.py\", line 162, in load_from_options\n    raise exceptions.MissingRequiredOptions(missing_required)\nkeystoneauth1.exceptions.auth_plugins.MissingRequiredOptions: Auth plugin requires parameters which were not given: auth_url\n",
        "module_stdout": "",
        "msg": "MODULE FAILURE",
        "rc": 0
    }
```
- Feature request
openstack driver should be able to fetch credentials from clouds.yml, similar to this example.
http://linchpin.readthedocs.io/en/develop/topologies_openstack.html#steps-to-provision-single-host

# Molecule and Ansible details

```
ansible --version
molecule --version
```

- Molecule installation method: One of source, pip
- Ansible installation method: One of source, pip, OS package

# Desired Behaviour

Please give some details of the feature being requested or what
should happen if providing a bug report.

# Actual Behaviour (Bug report only)

Please give some details of what is actually happening.
Include a [minimum complete verifiable example](http://stackoverflow.com/help/mcve) with
output of running `molecule --debug`.

**Comment by retr0h** [comment]
Looking at this [example](http://blog.oddbit.com/2015/10/26/ansible-20-new-openstack-modules/).  

> In the absence of any authentication information provided in your Ansible playbook, these modules will attempt to use the standard suite of OS_* variables (OS_USERNAME, OS_PASSWORD, etc). This is fine for testing, but you usually want to provide some sort of authentication configuration in your Ansible environment.

So if your clouds.yml contained something like:

```
clouds:
  testing:
    auth:
      auth_url: http://openstack.local:5000/v2.0
      username: admin
      password: secret
      project_name: admin
```

Then you need to update the create and destroy playbooks with the appropriate `cloud` option.  Molecule cannot account for everyones configuration differences.

```
- os_image:
    cloud: testing
```

**Comment by bhavikbhavsar** [comment]
Ok thanks for the update, will try to configure this correctly.
If possible do share any sample tried example that would be very much helpful.
