### ISSUE TITLE
Vagrant provider tries to destroy non-existent boxes

### ISSUE THREAD

**Issue by baccenfutter** [metacloud/molecule#934]
# Issue 

- Bug report

# Molecule and Ansible details

```
# ansible --version
ansible 2.3.2.0

# molecule --version
molecule, version 2.0.0.0rc16

# vagrant --version
Vagrant 1.9.6

# and
virtualbox-5.0.40.115130
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

```bash
cd myrole
molecule init scenario -r myrole -s default -d vagrant
molecule test
```

Should execute the test matrix using Vagrant/VirtualBox.

# Actual Behaviour (Bug report only)

Instead, the `destroy.yml` crashes with the following error:
```
--> Test matrix
    
└── default
    ├── destroy
    ├── dependency
    ├── syntax
    ├── create
    ├── converge
    ├── idempotence
    ├── lint
    ├── side_effect
    ├── verify
    └── destroy
--> Scenario: 'default'
--> Action: 'destroy'
    Using /home/baccenfutter/src/github.com/blunix/blunix-ansible/roles/blunix.role-certbot/molecule/default/.molecule/ansible.cfg as config file
    
    PLAYBOOK: destroy.yml **********************************************************
    1 plays in /home/baccenfutter/src/github.com/blunix/blunix-ansible/roles/blunix.role-certbot/molecule/default/destroy.yml
    
    PLAY [Destroy] *****************************************************************
    META: ran handlers
    
    TASK [Destroy molecule instance(s)] ********************************************
    task path: /home/baccenfutter/src/github.com/blunix/blunix-ansible/roles/blunix.role-certbot/molecule/default/destroy.yml:13
    Using module file /home/baccenfutter/.virtualenvs/blunix-ansible/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: baccenfutter
    <127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/baccenfutter/.ansible/tmp/ansible-tmp-1504165075.86-62464035820786 `" && echo ansible-tmp-1504165075.86-62464035820786="` echo /home/baccenfutter/.ansible/tmp/ansible-tmp-1504165075.86-62464035820786 `" ) && sleep 0'
    <127.0.0.1> PUT /tmp/tmpoZFPjL TO /home/baccenfutter/.ansible/tmp/ansible-tmp-1504165075.86-62464035820786/molecule_vagrant.py
    <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/baccenfutter/.ansible/tmp/ansible-tmp-1504165075.86-62464035820786/ /home/baccenfutter/.ansible/tmp/ansible-tmp-1504165075.86-62464035820786/molecule_vagrant.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '/home/baccenfutter/.virtualenvs/blunix-ansible/bin/python2 /home/baccenfutter/.ansible/tmp/ansible-tmp-1504165075.86-62464035820786/molecule_vagrant.py; rm -rf "/home/baccenfutter/.ansible/tmp/ansible-tmp-1504165075.86-62464035820786/" > /dev/null 2>&1 && sleep 0'
    The full traceback is:
    Traceback (most recent call last):
      File "/tmp/ansible_dQlLt8/ansible_module_molecule_vagrant.py", line 417, in <module>
        main()
      File "/tmp/ansible_dQlLt8/ansible_module_molecule_vagrant.py", line 413, in main
        v.destroy()
      File "/tmp/ansible_dQlLt8/ansible_module_molecule_vagrant.py", line 306, in destroy
        cd = self._created()
      File "/tmp/ansible_dQlLt8/ansible_module_molecule_vagrant.py", line 327, in _created
        status = self._status()
      File "/tmp/ansible_dQlLt8/ansible_module_molecule_vagrant.py", line 322, in _status
        s = self._vagrant.status(vm_name=instance_name)[0]
      File "/home/baccenfutter/.virtualenvs/blunix-ansible/lib/python2.7/site-packages/vagrant/__init__.py", line 493, in status
        output = self._run_vagrant_command(['status', '--machine-readable', vm_name])
      File "/home/baccenfutter/.virtualenvs/blunix-ansible/lib/python2.7/site-packages/vagrant/__init__.py", line 976, in _run_vagrant_command
        env=self.env, stderr=err_fh))
      File "/usr/lib64/python2.7/subprocess.py", line 219, in check_output
        raise CalledProcessError(retcode, cmd, output=output)
    subprocess.CalledProcessError: Command '['/usr/bin/vagrant', 'status', '--machine-readable', 'instance']' returned non-zero exit status 1
    
    failed: [localhost] (item={'box': u'ubuntu/xenial64', 'name': u'instance'}) => {
        "failed": true, 
        "item": {
            "box": "ubuntu/xenial64", 
            "name": "instance"
        }, 
        "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_dQlLt8/ansible_module_molecule_vagrant.py\", line 417, in <module>\n    main()\n  File \"/tmp/ansible_dQlLt8/ansible_module_molecule_vagrant.py\", line 413, in main\n    v.destroy()\n  File \"/tmp/ansible_dQlLt8/ansible_module_molecule_vagrant.py\", line 306, in destroy\n    cd = self._created()\n  File \"/tmp/ansible_dQlLt8/ansible_module_molecule_vagrant.py\", line 327, in _created\n    status = self._status()\n  File \"/tmp/ansible_dQlLt8/ansible_module_molecule_vagrant.py\", line 322, in _status\n    s = self._vagrant.status(vm_name=instance_name)[0]\n  File \"/home/baccenfutter/.virtualenvs/blunix-ansible/lib/python2.7/site-packages/vagrant/__init__.py\", line 493, in status\n    output = self._run_vagrant_command(['status', '--machine-readable', vm_name])\n  File \"/home/baccenfutter/.virtualenvs/blunix-ansible/lib/python2.7/site-packages/vagrant/__init__.py\", line 976, in _run_vagrant_command\n    env=self.env, stderr=err_fh))\n  File \"/usr/lib64/python2.7/subprocess.py\", line 219, in check_output\n    raise CalledProcessError(retcode, cmd, output=output)\nsubprocess.CalledProcessError: Command '['/usr/bin/vagrant', 'status', '--machine-readable', 'instance']' returned non-zero exit status 1\n", 
        "module_stdout": "", 
        "msg": "MODULE FAILURE", 
        "rc": 0
    }
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1   
    
    
ERROR: 
```

Looks like Molecule tries to destroy the instance without checking if it actually exists. Destroying a non-existent Vagrant box causes Vagrant to error:

```
# vagrant status --machine-readable instance
1504164744,,ui,error,The machine with the name 'instance' was not found configured for\nthis Vagrant environment.
1504164744,,error-exit,Vagrant::Errors::MachineNotFound,The machine with the name 'instance' was not found configured for\nthis Vagrant environment.
```

**Comment by retr0h** [comment]
Looks like your state might be goofed up.  If you `rm -rf molecule/default/.molecule/` does that clear things up?

**Comment by baccenfutter** [comment]
Solved. Thx @retr0h.
