### ISSUE TITLE
AttributeError: 'module' object has no attribute 'merge'

### ISSUE THREAD

**Issue by rakeshtechie** [metacloud/molecule#938]
# Issue Type

- Bug report
# Molecule and Ansible details

```
ansible --version
ansible 2.3.2.0

molecule --version
molecule, version 2.0.2.dev6

```

# Actual Behaviour (Bug report only)
i have initialized a new role and trying to test , using molecule test and am facing below issue
Traceback (most recent call last):
  File "/usr/local/bin/molecule", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/raavula/molecule/molecule/molecule/command/test.py", line 93, in test
    base.get_configs(args, command_args), scenario_name)
  File "/home/raavula/molecule/molecule/molecule/command/base.py", line 119, in get_configs
    ansible_args=ansible_args, ) for c in glob.glob(MOLECULE_GLOB)
  File "/home/raavula/molecule/molecule/molecule/config.py", line 90, in __init__
    self.config = self._combine()
  File "/home/raavula/molecule/molecule/molecule/config.py", line 249, in _combine
    base = self.merge_dicts(base, util.safe_load(interpolated_config))
  File "/home/raavula/molecule/molecule/molecule/config.py", line 214, in merge_dicts
    return merge_dicts(a, b)
  File "/home/raavula/molecule/molecule/molecule/config.py", line 385, in merge_dicts
    anyconfig.merge(a, b, ac_merge=MERGE_STRATEGY) AttributeError: 'module' object has no attribute 'merge'

i have checked anyconfig python package and looks like issue is with parameter ac_merge in config.py

can anyone advise if am missing anything ?

**Comment by retr0h** [comment]
what version of anyconfig are you using?

**Comment by rakeshtechie** [comment]
thanks for your the response @retr0h 

i have forked this repo and installed in my machine, i think i need to re-install to get it correct.

regarding anyconfig, its "version - 0.7.0"

**Comment by retr0h** [comment]
You're using an old version of anyconfig.  If you pip install molecule it will install the proper [version](https://github.com/metacloud/molecule/blob/master/requirements.txt#L2).

**Comment by rakeshtechie** [comment]
i updated molecule to latest version and all good now, i can run molecule commands without issue

Thank you @retr0h
