### ISSUE TITLE
Molecule fails when trying to add `config_options` to Ansible provisioner

### ISSUE THREAD

**Issue by viniciusfs** [metacloud/molecule#982]
# Issue Type

- Bug report

# Molecule and Ansible details

```
ansible --version
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/home/vfigueiredo/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vfigueiredo/Code/.virtualenvs/ansible-personal/local/lib/python2.7/site-packages/ansible
  executable location = /home/vfigueiredo/Code/.virtualenvs/ansible-personal/bin/ansible
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

molecule --version
molecule, version 2.1.0
```

- Molecule installation method: pip
- Ansible installation method: pip

# Desired Behaviour

When adding configuration keys to Ansible provisioner desired behaviour is Molecule read and apply those configurations.

# Actual Behaviour

Actual behaviour is Molecule failing looking for `MOLECULE_FILE` key/environment variable.

```
$ molecule --debug test -s default -d vagrant
--> Test matrix
    
└── default
    ├── destroy
    ├── dependency
    ├── syntax
    ├── create
    ├── converge
    ├── idempotence
    ├── lint
    ├── side_effect
    ├── verify
    └── destroy
--> Scenario: 'default'
--> Action: 'destroy'
DEBUG: ANSIBLE ENVIRONMENT
---
ANSIBLE_CONFIG: /home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default/.molecule/ansible.cfg
ANSIBLE_FILTER_PLUGINS: /home/vfigueiredo/Code/.virtualenvs/ansible-personal/local/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/filters:/home/vfigueiredo/ownCloud/Code/ansible-role-epel/plugins/filters:/home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default/.molecule/plugins/filters
ANSIBLE_LIBRARY: /home/vfigueiredo/Code/.virtualenvs/ansible-personal/local/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/libraries:/home/vfigueiredo/ownCloud/Code/ansible-role-epel/library:/home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default/.molecule/library
ANSIBLE_ROLES_PATH: /home/vfigueiredo/ownCloud/Code:/home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default/.molecule/roles

DEBUG: MOLECULE ENVIRONMENT
---
MOLECULE_DEBUG: 'True'
MOLECULE_DEPENDENCY_NAME: galaxy
MOLECULE_DRIVER_NAME: vagrant
MOLECULE_EPHEMERAL_DIRECTORY: /home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default/.molecule
MOLECULE_FILE: /home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default/molecule.yml
MOLECULE_INSTANCE_CONFIG: /home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default/.molecule/instance_config.yml
MOLECULE_INVENTORY_FILE: /home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default/.molecule/ansible_inventory.yml
MOLECULE_LINT_NAME: yamllint
MOLECULE_PROVISIONER_NAME: ansible
MOLECULE_SCENARIO_DIRECTORY: /home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default
MOLECULE_SCENARIO_NAME: default
MOLECULE_VERIFIER_NAME: testinfra

DEBUG: COMMAND
/home/vfigueiredo/Code/.virtualenvs/ansible-personal/bin/ansible-playbook --inventory=/home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default/.molecule/ansible_inventory.yml --diff /home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default/destroy.yml -vvv
    ansible-playbook 2.4.0.0
      config file = /home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default/.molecule/ansible.cfg
      configured module search path = [u'/home/vfigueiredo/Code/.virtualenvs/ansible-personal/local/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/libraries', u'/home/vfigueiredo/ownCloud/Code/ansible-role-epel/library', u'/home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default/.molecule/library']
      ansible python module location = /home/vfigueiredo/Code/.virtualenvs/ansible-personal/local/lib/python2.7/site-packages/ansible
      executable location = /home/vfigueiredo/Code/.virtualenvs/ansible-personal/bin/ansible-playbook
      python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
    Using /home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default/.molecule/ansible.cfg as config file
    Parsed /home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default/.molecule/ansible_inventory.yml inventory source with yaml plugin
    
    PLAYBOOK: destroy.yml **********************************************************
    1 plays in /home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default/destroy.yml
    
    PLAY [Destroy] *****************************************************************
    META: ran handlers
    
    TASK [Destroy molecule instance(s)] ********************************************
    task path: /home/vfigueiredo/ownCloud/Code/ansible-role-epel/molecule/default/destroy.yml:13
    Using module file /home/vfigueiredo/Code/.virtualenvs/ansible-personal/lib/python2.7/site-packages/molecule/provisioner/ansible/plugins/libraries/molecule_vagrant.py
    <127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: vfigueiredo
    <127.0.0.1> EXEC /bin/sh -c 'echo ~ && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/vfigueiredo/.ansible/tmp/ansible-tmp-1507206897.54-217657537177161 `" && echo ansible-tmp-1507206897.54-217657537177161="` echo /home/vfigueiredo/.ansible/tmp/ansible-tmp-1507206897.54-217657537177161 `" ) && sleep 0'
    <127.0.0.1> PUT /tmp/tmpTQJ06l TO /home/vfigueiredo/.ansible/tmp/ansible-tmp-1507206897.54-217657537177161/molecule_vagrant.py
    <127.0.0.1> EXEC /bin/sh -c 'chmod u+x /home/vfigueiredo/.ansible/tmp/ansible-tmp-1507206897.54-217657537177161/ /home/vfigueiredo/.ansible/tmp/ansible-tmp-1507206897.54-217657537177161/molecule_vagrant.py && sleep 0'
    <127.0.0.1> EXEC /bin/sh -c 'sudo -H -S -n -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-szoqbhmvgzvrqkkghxnkhrkaovlxdsod; /home/vfigueiredo/Code/.virtualenvs/ansible-personal/bin/python2 /home/vfigueiredo/.ansible/tmp/ansible-tmp-1507206897.54-217657537177161/molecule_vagrant.py; rm -rf "/home/vfigueiredo/.ansible/tmp/ansible-tmp-1507206897.54-217657537177161/" > /dev/null 2>&1'"'"' && sleep 0'
    The full traceback is:
    Traceback (most recent call last):
      File "/tmp/ansible_xshVSK/ansible_module_molecule_vagrant.py", line 417, in <module>
        main()
      File "/tmp/ansible_xshVSK/ansible_module_molecule_vagrant.py", line 407, in main
        v = VagrantClient(module)
      File "/tmp/ansible_xshVSK/ansible_module_molecule_vagrant.py", line 287, in __init__
        self._config = self._get_config()
      File "/tmp/ansible_xshVSK/ansible_module_molecule_vagrant.py", line 333, in _get_config
        molecule_file = os.environ['MOLECULE_FILE']
      File "/home/vfigueiredo/Code/.virtualenvs/ansible-personal/lib/python2.7/UserDict.py", line 40, in __getitem__
        raise KeyError(key)
    KeyError: 'MOLECULE_FILE'
    
    failed: [localhost] (item={'box': u'viniciusfs/centos7', 'name': u'centos7'}) => {
        "changed": false, 
        "failed": true, 
        "item": {
            "box": "viniciusfs/centos7", 
            "name": "centos7"
        }, 
        "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_xshVSK/ansible_module_molecule_vagrant.py\", line 417, in <module>\n    main()\n  File \"/tmp/ansible_xshVSK/ansible_module_molecule_vagrant.py\", line 407, in main\n    v = VagrantClient(module)\n  File \"/tmp/ansible_xshVSK/ansible_module_molecule_vagrant.py\", line 287, in __init__\n    self._config = self._get_config()\n  File \"/tmp/ansible_xshVSK/ansible_module_molecule_vagrant.py\", line 333, in _get_config\n    molecule_file = os.environ['MOLECULE_FILE']\n  File \"/home/vfigueiredo/Code/.virtualenvs/ansible-personal/lib/python2.7/UserDict.py\", line 40, in __getitem__\n    raise KeyError(key)\nKeyError: 'MOLECULE_FILE'\n", 
        "module_stdout": "", 
        "msg": "MODULE FAILURE", 
        "rc": 0
    }
    
    PLAY RECAP *********************************************************************
    localhost                  : ok=0    changed=0    unreachable=0    failed=1   
    
    
ERROR: 

vfigueiredo@SUP6698N.appi.corp.local ~/ownCloud/Code/ansible-role-epel [master ]  [ansible-personal] 
```
Here is my `molecule.yml`:
```
---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

lint:
  name: yamllint

platforms:
  - name: centos7
    box: viniciusfs/centos7

provisioner:
  name: ansible
  options:
    vvv: True
  config_options:
    privilege_escalation:
      become: True
      become_method: sudo
      become_user: root
  lint:
    name: ansible-lint

scenario:
  name: default

verifier:
  name: testinfra
  lint:
    name: flake8
```
Molecule works after removing `config_options` key from `molecule.yml`.

**Comment by retr0h** [comment]
Same problem here as in #983.
